---
title: "Two Parameters B"
tutorial:
  id: "two-parameters-b"
output:
  learnr::tutorial:
      progressive: true
      allow_skip: true
runtime: shiny_prerendered
description: "Chapter 7 tutorial part B"
---


```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(primer.data)
library(skimr)
library(rstanarm)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

```{r copy-code-chunk, child = "../../child_documents/copy_button.Rmd"}
```

```{r info-section, child = "../../child_documents/info_section.Rmd"}
```

## Preliminaries

### Exercise 1

Use `skim()` from the `skimr` package to skim the data set `trains`.

```{r preliminaries-ex-1, exercise = TRUE}

```

<button onclick = "transfer_code(this)">Copy previous code</button>

```{r preliminaries-ex-1-hint, eval = FALSE}

```

###



## Wisdom

## Justice

## Courage

## Temperance

```{r download-answers, child = "../../child_documents/download_answers.Rmd"}
```
