---
title: 'Probability: Permutation Tests'
author: Yuhan Wu
tutorial:
  id: probability-permutation-tests
output:
  learnr::tutorial:
    progressive: yes
    allow_skip: yes
runtime: shiny_prerendered
description: Explain what a permutation test is and give examples of its use.
---

```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(primer.data)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

```{r copy-code-chunk, child = "../../child_documents/copy_button.Rmd"}
```

```{r info-section, child = "../../child_documents/info_section.Rmd"}
```

<!-- Reread Chapter 4. Create a nice plot which shows the result of a permutation test, and then guide the student to doing it. Use this for background: https://www.youtube.com/watch?v=GmvpsJHGCxQ 
https://www.youtube.com/watch?v=rJ3AZCQuiLw
-->

## Permutation tests
### 

```{r download-answers, child = "../../child_documents/download_answers.Rmd"}
```
