---
title: Mapping
tutorial:
  id: mapping
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: Mapping data in R
---


```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(primer.data)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

```{r copy-code-chunk, child = "../../child_documents/copy_button.Rmd"}
```

```{r info-section, child = "../../child_documents/info_section.Rmd"}
```

<!-- CHECKLIST BEFORE STARTING: -->
<!-- * Load necessary libraries for tutorial in the first code chunk -->
<!-- * Edit yaml at the START OF THIS FILE -->
<!-- * Review: https://ppbds.github.io/primer.tutorials/articles/instructions.html -->


<!-- ## First section (use sentence case) -->
<!-- ### -->

## Map Basics
###

You've likely heard of longitude and latitude.


```{r download-answers, child = "../../child_documents/download_answers.Rmd"}
```
