---
title: "Assignment Management"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Assignment Management}
  %\usepackage[UTF-8]{inputenc}
---

```{r not-setup, include = FALSE}
library(knitr)
```

Overview:

- Goal
- Components
- Pipeline

## Goal

The point of this document is to plan and lay out the details of a work submission pipeline for assignments related to primer tutorials.

The goal is to have students do an assignment, download the RDS, and email the RDS file to a Gmail account. After the submission deadline is reached, the teacher simply has to run an R script and all the student submissions will be collected into a Gdrive and tallied.

The output will be a dataframe with six columns for each student: email, last name, first name, count of how many questions were answered, total time spent, and a link to the submitted rds file.

## [Set up your OAuth Account first!](oauth_walkthrough.html)

## Components

### Gmail

This is the "submission pile" of the processing pipeline. People will send their submissions here for processing.

An important element to note is that likely the submissions will be collected based on TITLE OF THE EMAIL. For example:

`Nuo Wen Lei; 000-getting-started`

Or some kind of structure like this, allowing the following processes to organize the submissions easily.

<!-- First script: Give me all the rds files submitted since Day X and containing a string like "000-getting-started" and Gdrive path in which to place results. (Script can check to make sure that path exists.) Create a folder on the Gdrive named "path/000-getting-started-YYYY-MM-DD" with all the rds files there.  -->

<!-- Second scrip: Takes Gdrive path, like "tutorials/000-getting-started-2021-08-23", confirms that it exists and has a bunch of rds files in it, and then creates, in that same location, the final csv. -->


### Google Apps Script with Callable API

Google Apps Script is an often under-appreciated service provided by Google. It allows communication between almost all of Gdrive and its various applications.

Here it will serve as the connector between Gmail, Gdrive, and the local R script. The purpose of this component is to receive an API call, which will include a few parameters:

- name of tutorial/assignment to collect
- date cutoffs (deadlines)
- other additional filters

Based on the parameters of the API call from an R script, the Apps Script will filter the Gmail attachments received and sort and download the submissions into the desired Gdrive folders.

Pseudo-code:

- get all received email names from Gmail
- filter by tutorial name, date received, number of attachments
- create new tutorial folder at correct location with the name of the tutorial
- fetch all relevant attachments from Gmail
- rename all attachments by tutorial name and student name
- save all attachments in new Gdrive tutorial folder
- return new tutorial folder name as success status to local script

The following link is [my source of inspiration for this component](http://www.googleappsscript.org/home/fetch-gmail-attachment-to-google-drive-using-google-apps-script).

### R Scripts

There will be a few R scripts since the entire pipeline will be split into multiple parts.

#### Main Script

This is the ONLY script that will be ran manually. Hopefully, the teacher can just run this and everything will work.

The output should be the `Submission_Aggregation_for_Entire_Class.csv` file for a specific tutorial

#### Helper Script

This will store all the components/functions that will be called in the main R script.

The functions will be:

- `collect_submissions_to_gdrive(tutorial_name, submission_start_date, submission_end_date)`

  - This function will call the Google Apps Script API, which will organize all the submissions and put it into Gdrive.

- `create_submission_aggregation(tutorial_name)`

  - This function will connect to the Gdrive account, process all the RDS files, and create and store the `Submission_Aggregation_for_Entire_Class.csv` into Gdrive while also storing a copy locally.
  
## Pipeline

##### Step 1: Run Main R Script

This should be the only thing done manually.

##### Step 2: Call R Helper function - `collect_submissions_to_gdrive()`

This is part 1 of the Main R Script.

##### Step 3: Call Google Apps Script API

This will organize and transfer the filtered tutorial submissions from Gmail to Gdrive.

##### Step 4: Call R Helper function - `create_submission_aggregation()`

This is part 2 of the Main R Script.

##### Step 5: Connect local device to Gdrive

This will allow access to the newly downloaded submissions and tutorial folder.

##### Step 6: Read all relevant RDS files from Gdrive and Generate Class-Aggregated Submission DataFrame

The dataframe is the desired result of the pipeline

##### Step 7: Save DataFrame in Appropriate Gdrive location and locally

Done!



