---
title: "Instructions for Writing Tutorials"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Instructions for Writing Tutorials}
  %\usepackage[UTF-8]{inputenc}
---

```{r not-setup, include=FALSE}
library(tidyverse)
#library(learnr)
```

*There are no questions here. There are only instructions!*

## Introduction

We are building the shallowest possible learning curve. Almost every student should be able to answer almost every Exercise, albeit perhaps with the help of the Hint. There are no hard questions. In fact, there really aren't *questions* at all. Instead, there are *instructions*. Do this. Then do that. Next do this other thing.

Assume that you are giving the student a private lesson. You ask them a question. They give you an answer. What would you say next to them? What do you want to teach them, given that context?

There are 100,000 bits of R knowledge which we might provide to students: tips, tricks, cool packages, fun websites, et cetera. We don't have time to mention all of them! The art of teaching is to, first, decide which 1,000 of the bits is most important to mention and, second, figure out the best time to mention them. Tutorials are a key location for doing that mentioning. Which bits do we mention and where do we mention them?


We are building a "pit of success." Generally, students don't do the assigned reading, at least in a large class. But, they will complete required work. They will do the tutorials. Our promise: If you complete the tutorials, you will become a data scientist. There is simply no way not to.


## Basic structure

Follow the [set up guide](https://ppbds.github.io/primer/set-up-for-working-on-the-primer.html) to fork/download a copy of [PPBDS/primer.tutorials](https://github.com/PPBDS/primer.tutorials). Press "Install and Restart" to ensure that you have the latest copy installed. (You should not do `remotes::install_github("PPBDS/primer.tutorials")` since that gets the version from Github. You want the version from your computer so that you get any changes you make.) Go to the Tutorial tab and press "Start Tutorial" for Visualization-A. This is how students run tutorials. Also, open the Rmd which creates this tutorial from `inst/tutorials/01-visualization-A/tutorial.Rmd`.

The beginning of every tutorial is an *Information* section which requires providing your name and email. The tutorial is then divided into different *Sections* that you see as side panels. Within these sections, there are a series of *Exercises* which can include writing code or writing text. At the end of the tutorial, there is a *Submit* section that provides students with instructions on how to download a copy of their answers. 

To create a new tutorial, use File -> New File -> R Markdown. Choose "From Template" option and then select "Primer Tutorial." The "Technical details" section at the end of this document provides an overview of the default material in the template. Change the `title`, `id`, and `description` parts of the YAML header. The title may include spaces. The `id` should be exactly the same as the `title`, but all in lower case and with spaces replaced with dashes. One sentence is enough for the description.

The `id` value is important. It should be the same as the directory in which the tutorial is located, but with the leading numbers removed. (We include numbers in the directory names so that the tutorials are sorted correctly in the Tutorial pane.) It is used for the name of the answer file which students save at the end of the tutorial. It is always all lower case with dashes instead of spaces.

### Sections

Tutorials are divided into *Sections* that are seen on the side panel. To create these sections, we include a double hash (##) before the text for it to show up as a side panel. This is also called the Group Title.  Use sentence case. Please also include a section identifier using {#id} (see example below), which will be used as part of the code chunk labels of the exercises in that section.

The hashes work like a sizing system. The group title (double hash ##) is the largest. When you want to make a header within that panel you increase the hash count by 1. 

Each section begins with a sentence or two about what this group of questions is trying to accomplish. Then add a triple hash `###` to cause the tutorial to pause before it goes to the first exercise. Example from the Tools tutorial:

````markdown
## The Terminal {#terminal}

The Terminal pane is next to the Console pane in the lower left portion of RStudio. We use the Console pane to talk to R. We use the Terminal pane to talk directly with your computer. Sadly, the Console and the Terminal speak different languages.

###

### Exercise 1

`r ''````{r terminal-1, exercise = True}

```

````

Each side panel is composed of a series of numbered exercises. To create the exercise headers, you use three hashes. Make sure you number your exercises -- `### Exercise 1`, `### Exercise 2` and so on. This makes it easy for students to refer to a specific location when they have a question.

### Hints

Tutorials should be so easy that 95% of the students can answer 95% of the questions easily, given that they have the Primer open as they work. One way to ensure that is to add a "hint" to almost every coding question.  (Written questions rarely need hints.)

Hints must always have the same code chunk name as the exercise chunk for which they are the hint, with a "-hint" added at the end. So, if an exercise code chunk is named "ex-1", then the hint associated with that exercise is named "ex-1-hint". A second hint for that same question would be named "ex-1-hint-2", and so on. We think that, if you want a two hints, yoy must also provide a number for the first hint: ex-1-hint-1, ex-1-hint-2 and so on. If you only have one hint, no number is necessary.

When you create a hint, always use `eval = FALSE` within the parentheses in the code chunk. This is because hints will often include "..." and other symbols which do not run as correct R code. So, we need to tell R not to run it or an error will occur during R CMD check.

Hints should NOT have comment characters (#) like this below. 

This is what a hint *should not* look like.

````markdown
`r ''````{r ex-1-hint-bad, eval = FALSE}
# You do not need a hash in front of text! 
```
````
This is what a hint *should* look like.

````markdown
`r ''````{r ex-1-hint-good, eval=FALSE}
This is an example hint. Normally sentences like these 
would cause an error in R because it is not proper code. 
However, since we inclued eval = FALSE in the r-chunk, 
R ignores all potential errors!
```
````

You need to wrap the text in a long hint by hand, inserting the carriage returns yourself. R will not wrap the text automatically.

Often, hints look like this

````markdown
`r ''````{r ex-1-hint, eval = FALSE}
... %>% 
  filter(year = ...) %>% 
  ...(flights)
```
````

The ... indicate places where the student needs to insert some code, a value or a function name. The code in hints should be formatted correctly.

In the current version of **learnr**, students can not see the first hint after clicking through to the next hint. So, make sure the last hint is the one you most want them to have access to, i.e., the one which provides the key information. If I can see the last hint, I should have no reason to consult any earlier hints.  

### Flow

Each Section begins with a few sentences which explain what this collection of exercises will teach us. Or it can "drop" some knowledge. But anything more than a short paragraph is much too much. Students won't read it. This portion is followed by with a triple hash on its own line. 

````markdown

###

````


This creates a "Continue" button  which students will have to click before they get to see the first exercise. This increases the odds (we hope!) that students will actually read the Section introduction.



#### Exercises

Each Exercise should have a "flow" which requires that students hit the "Continue" button at least twice, and potentially more often. 

* Each Exercise begins with a sentence or two of knowledge and/or the question itself. If the length of the text is longer than one or two lines on the knitted Rmd, then do not show the exercise code chunk in the same part. Instead, the introduction is followed by the triple hashes, thereby creating the Continue button. If the length of the text is short enough that students are willing to read it (at most 2 lines), you can include the code chunk in the same part.

* Then follows the exercise code chunk, along with any hint code chunks --- and there should almost always be a hint or two. These code chunks are also followed by the triple hash. We want students to pause after they have run their code submissions.

* The last part of the Exercise is another knowledge drop. Again, this can't be more than a sentence or two. But it should be more substantive than a simple "Good job." Again, this is an occasion to drop some knowledge. Use it. Of the 1,000 items which we want to mention, which one belongs here because it connects to the question/answer which students have just completed.



#### Code answers

Good questions generate results when the student presses Run Code. Ideally, they press run code, see their results, hit Continue, and then see our answer to the same question. They can then confirm for themselves, immediately, that they got the right answer.

Never hard code a number. Use R to inline calculate it. 


#### Permanent objects

Permanent objects should do something.

#### Set up questions

In many settings, it is natural for a set up question to have three parts. First, run a line of code that reports on the value of something. Example:

````markdown
rstudioapi::readRStudioPreference(name = "load_workspace", default = "Code failed.")
````

This will return TRUE, which is the default value. 

Second, change the setting. This generally won't return anything.

````markdown
rstudioapi::writeRStudioPreference(name = "load_workspace", value = FALSE)
````

See how the first was "read" and the second was "write"? Then, the third and final step is to confirm that the change worked by re-running the first code again.

````markdown
rstudioapi::readRStudioPreference(name = "load_workspace", default = "Code failed.")
````

And finish with a sentence that tells the student to notice that the value has changed and that it is now correct. (Of course, we "monitor" that by making them copy/paste this last command and its return from the Console into the tutorial.)


## Question types

### Text questions

Text questions look like the below. The actual question should be written above the code chunk. As always, the code chunk must have a name. Replace the `6` with the number of rows you want the answer box to have.

````markdown
### Exercise 2

Write about four sentences explaining, in your own words, the meaning of the motto "No causation without manipulation."

`r ''````{r CHANGE_THIS_NAME}
question_text(NULL,
    answer(NULL, correct = TRUE),
    allow_retry = TRUE,
    try_again_button = "Edit Answer",
    incorrect = NULL,
    options = list(nrows = 6))
```
````

Obviously, you should change the name of the code chunk since duplicate names are not allowed in a tutorial.

Currently, hints are not available for this type of question, see thread for detail:
https://community.rstudio.com/t/hints-in-written-questions/108184

### Graphic questions

The most common question grouping involves a graphic. You want to first show the graphic that you will create by the end. You show it once at the start of the group and once before the last exercise, as a reminder of what the graphic should look like so users do not need to scroll all the way back up. 

You should put the code for the graph in the code chunk at the start of the section. Save the code to an object. The name of the object should have a _p suffix, where the "p" stands for "plot." This way, you only have to put the object name in the code chunk at the end of the section rather than copying the code.

You then build up the graphic, line by line, over the series of exercises, providing hints along the way. Along the way, it is fine to have a hint which reports: "This is what your code should look like now." That allows a student who is confused to catch. But don't do that too often since it will cause students to just look ahead to get the right answer.


### Lessons

Add comments which appear after they press the run code button, providing a sentence or two (no more) of commentary. 

Place the solution comment two lines after ### so that students will be able to solve the problem and press continue before seeing the comment.  

Each code should always spit out something. Interactivity is good! Students should always look at what their code is spitting out. Perhaps the hint could always show the spit out also? That is how they know that their answer is correct! Only the last step puts an assignment operator at the top of the pipe, and often not even then.


Do not create interim results for a large chunk of code. Favor building a large chunk of code with pipes instead. The final graphic is built in one long pipe.

Never instruct a student to replace an object with a different object with the same name. 

Prevent quotes from turning into curly quotes by writing `"nnet"` instead of "nnet". You never want curly quotes in something which might be copy/pasted to the prompt. 

Follow our Code Style Guide, especially spaces around operators like " = ". Use only one command per line in pipes and graphics, with proper indentation. Indent plotting commands after ggplot().


Do not create an object in one question and then assume that it will be available in subsequent questions. It won't be! Each question is independent of every other question. They live in separate R instances. The two exceptions to this is, first, code in the "setup" chunk for a question will be run and anything created will be available, but just in that question. Second (and this seems buggy and unreliable!) objects created in the initial setup chunk for the entire tutorial are available in all later questions, just the way that library() commands executed there do not need to be executed again. 

**Just putting code in a random R code chunk does not guarantee that that object will be available elsewhere, although it sometimes is!** Lesson is that, if you have an object you need just once, then create it in a setup chunk for that question. If you have an object you will need in multiple questions, create it in the setup chunk at the top of the lesson. TW thinks that you can use random R code chunks to do things, **but you must give those code chunks a name**.



<!-- DK: Check this next claim out. Doesn't the new R text constant make this unnecessary? How should we do it now? -->

<!-- https://mpopov.com/blog/2020/05/22/strings-in-r-4.x/ -->

<!-- MY hypothesis is that ycontrol = c("$$13 - \\tau_M$$") can become something like ycontrol = c(r"$13 - \tau_M$") -->

You will generally need to backslashes when using math notation in `question_text()`, e.g., ````$\\tau$```` in place of ````$\tau$````.  

The exercise code chunk should not have zero lines. It can be blank, but it must have at least one empty line.

Code chunks for questions must be named. Don't worry about the naming/numbering, as long as the code chunks don't have duplicate names.

Do not provide official learnr answers. There is no need to grade what the students submit. You may sometimes provide answers in a comment outside the code chunk, as a service to others authors working on the tutorial. Use your best judgment.


## Inputs

### Using data

Use built-in data sets in constructing tutorial questions, or use data sets which you create yourself in the tutorial. Note that several packages from the **tidyverse** have built in data, although it is worth making sure that they are tibbles rather than data frames. To see all the data sets in the Tidyverse, type `library(tidyverse)` first.  Then, you can look at these with --- `data()` --- and then looking for data sets associated with **tidyverse** packages. You can also use data sets from **primer.data**.

### Using images

For unknown reasons, our usual way of including images in an Rmd file does not work in tutorials. (Probably cause is something to do with Shiny.) The workaround is to include the **png** and **grid** packages in your setup chunk and then use code like:

````markdown
`r ''````{r}
file <- system.file("images/excel_2.png", 
                     package = "primer.tutorials")
img <- readPNG(file)
grid.raster(img)
```
````

All images should be placed in inst/images. Sub-directories could be created under this but have not been needed. Note how we give the full path to the target file. This is highly recommended, lest weird path issues develop on Windows machines.

### Using files

<!-- DK: Explain what each code chunk is doing. -->

If you want to distribute a file which will be used by a tutorial, you place that file in inst/www. (You may want to do that first, submit a PR, and then, once it is quickly accepted, the file will be available on Github for you to use in the tutorial.) To see how to use such a file, check out out Data A. Consider this example:

````markdown
### Exercise 1

`r ''````{r ex-1-setup}
file.copy(system.file("www/test_1.csv", 
                      package = "primer.tutorials"), ".")
```

Consider the contents of the `test_1.csv` file.

`r ''````{r, comment=''}
cat(readLines(system.file("www/test_1.csv", package = "primer.tutorials")), sep = "\n")
```

###

Write code to read this file into R.

`r ''````{r ex-1, exercise = TRUE}

```

`r ''````{r ex-1-hint, eval = FALSE}
Use read_csv() to read in a csv file. 
Set the `file` argument to "test_1.csv".
```

`r ''````{r ex-2-hint, eval = FALSE}
read_csv(file = "...")
```

###

The result when your code is run should look like this:

`r ''````{r}
read_csv(system.file("www/test_1.csv", package = "primer.tutorials"))
```

###

The column specification message is a suggestion to specify the data types for each column of data. R "guesses" a data type until you do. For now, ignore the message. You will resolve this issue in a later exercise.
````

## Before submitting a pull request

### Check tutorial functionality 

Once you are done writing your tutorial, you need to make sure it works before you submit a pull request.

1. Click "Install and Restart" from the Build tab. Then, hit "Start Tutorial" in the Tutorial tab. This mimics the experience that users will have. This will catch some common errors, like having two code chunks with the same name.

2. Do a full test, which means running R CMD check. Go to the top right window of RStudio. Click the Build pane and hit the "Check" button (with the green check mark). You will then see a bunch of code and tests running. The most important is to make sure it says "OK" next to “testthat”. You should always run this before submitting a pull request.

Question: Is there ever reason to do 1) if 2) works fine? Not that I know of.

### What To Do If Check Fails

1. Read the error message at the bottom of the Build pane. You want to see "R CMD check succeeded." If not, there is a problem. The error message will often provide a clue as to where in your code the error occurred.

2. If that error message is not detailed enough, go to the `primer.data.rcheck` folder, which should be located in the same directory as `primer.data`. This is a folder created by the R CMD check process, and it will delete when the check process succeeds. If the process fails, the `primer.data.rcheck` folder stays around so that you can examine it. The key file in there is `testthat.Rout.fail`, which should be in the `tests` directory. It has more details.

The most common source of errors is something wrong with the hint code chunks, which are not evaluated when you just Run Document. Make sure the `eval = FALSE` is set in the code chunk for all hints. Check also to see if you included the Information and Submission lines. 



## Technical details

This section reviews some of the technical details behind the special modifications we have made to the basic tutorial technology. It is only of interest to those thinking of modifying the current approach.

### YAML and setup code chunk

The top of your file should look like the text below.

````markdown
---
title: "Data API"
tutorial:
  id: "data-api"
output:
  learnr::tutorial:
      progressive: true
      allow_skip: true
runtime: shiny_prerendered
description: "Working with APIs (application programming interfaces) to download data."
---

`r ''````{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

`r ''````{js change-code, echo = FALSE}

function transfer_code(elem){
  Shiny.setInputValue("js_to_server", elem.previousElementSibling.dataset.label);
  
}

Shiny.addCustomMessageHandler('set-exercise-code', function(x) {
  var el = $(`.tutorial-exercise[data-label="${x.label}"] .tutorial-exercise-code-editor`)
  var exerciseInput = Shiny.inputBindings.bindingNames["tutorial.exerciseInput"].binding
  exerciseInput.setValue(el, {code: x.code});
  Shiny.setInputValue("js_to_server", null);
})
```

`r ''````{r observe-transfers, context = "server"}

observeEvent(input$js_to_server, {
  ex_next = input$js_to_server
  str_num = parse_integer(gsub("[^0-9]", "", ex_next)) - 1
  str_head = gsub("[0-9]", "", ex_next)
  ex_prev = paste0(str_head, str_num)
  code <- learnr:::get_exercise_submission(session, ex_prev)$data$code %>% trimws()
  session$sendCustomMessage("set-exercise-code", list(label = ex_next, code = code))
})
```
````

Every tutorial must load the **learnr** package in order to function. `library(primer.tutorials)` is always included because it contains the file, `submissions_functions.R`, which enables answer downloading. All our tutorials need the **tidyverse**. You may need to add other packages which are used in your tutorial. Any such packages also need to be included in the DESCRIPTION file.

`echo = FALSE` is a handy default because, most of the time, we don't show users the code. Setting the `tutorial.exercise.timelimit` to 60 seconds is safe, but probably not necessary. `tutorial.storage` must be set to `local` to ensure that user work is saved between sessions.


### Information section

The first question should ask students to give us their name and email. (This way, when we generate a file with the student's responses, their name/email is included in that file). Use this *exactly*:

````markdown
## Information
###

`r ''````{r information}
quiz(caption = "",
  question_text(
    "Name:",
    answer(NULL, correct = TRUE),
    allow_retry = TRUE,
    try_again_button = "Edit Answer",
    incorrect = NULL),
  question_text(
    "Email:",
    answer(NULL, correct = TRUE),
    allow_retry = TRUE,
    try_again_button = "Edit Answer",
    incorrect = NULL))
```
````

R CMD check will test that all tutorials have this section exactly (more or less) as we have it here.

### Submit section

The last section panel of your tutorial must be the Submit section. This prints out instructions for students to download an .rds file to be submitted. Every detail matters, including the `context` values and the lack of parentheses after `submission_ui`. Note that there is no need for a triple hash below `## Submit`.

````markdown
## Submit

`r ''````{r context = "setup"}
submission_ui
```

`r ''````{r context = "server"}
submission_server()
```

````

R CMD check will confirm that these lines appear at the end of every tutorial, as with the Information section. If you forget the Submission lines, the tutorial will successfully run but the build check will fail, which can make it harder to identify what is going on. 

If either the Introduction or Submit sections are missing, R CMD check will return something like "From test-components.R. Submission (or Information) lines missing from file".


### Copy button comments

To implement buttons that allow students to copy code from the previous exercise to the current one, first you have to add the following 2 code chunks **right after the `set-up` chunk** at the top of the file:

**Necessary Code Chunks:** (It's assumed that you have loaded in the `tidyverse` package)

````markdown
`r ''````{js change-code, echo = FALSE}

function transfer_code(elem){
  Shiny.setInputValue("js_to_server", elem.previousElementSibling.dataset.label);
  
}

Shiny.addCustomMessageHandler('set-exercise-code', function(x) {
  var el = $(`.tutorial-exercise[data-label="${x.label}"] .tutorial-exercise-code-editor`)
  var exerciseInput = Shiny.inputBindings.bindingNames["tutorial.exerciseInput"].binding
  exerciseInput.setValue(el, {code: x.code});
  Shiny.setInputValue("js_to_server", null);
})
```

`r ''````{r observe-transfers, context = "server"}

observeEvent(input$js_to_server, {
  ex_next = input$js_to_server
  str_num = parse_integer(gsub("[^0-9]", "", ex_next)) - 1
  str_head = gsub("[0-9]", "", ex_next)
  ex_prev = paste0(str_head, str_num)
  code <- learnr:::get_exercise_submission(session, ex_prev)$data$code %>% trimws()
  session$sendCustomMessage("set-exercise-code", list(label = ex_next, code = code))
})
```
````

**Example:**
Then you can place buttons AFTER an exercise code chunk like below:

````markdown

`r ''````{r exercise-1, exercise = TRUE}

```

`r ''`<button onclick="transfer_code(this)">Copy previous code</button>

`r ''````{r exercise-1-hint, eval = FALSE}

```

````

If you want to include a hint and the button, you must add the hint AFTER the button like shown.

**Explanation:**

For the setup code chunks, the first chunk is written in javascript and the second is written in R.

The pipeline works as such:

1. When a button to transfer code is clicked, it triggers the `"onclick"` event, which calls the function `transfer_code()`, passing the button element itself as an argument.

2. `transfer_code()` is a javascript function defined in the first code chunk that retrieves the current exercise label from an html element after it is compiled. This works by selecting the desired html element relative to the button element passed from the `"onclick"` event. The function then sets a Shiny server input variable called `js_to_server` to the current exercise label.

3. The action of setting `js_to_server` to a new variable triggers a Shiny server event defined in the second code chunk. This event gets the previous exercise's submission and sends that code as well as the current exercise label back to javascript through a custom Shiny message called `"set-exercise-code"`.

4. The message is received in javascript in the first code chunk. Javascript then finds the current code chunk and then **overwrites** the text in the current code chunk with the text from the previous code chunk.

**Process to Current Stage:**
This function was suggested by Preceptor for simpler user experience in long tutorials that require pipe-building across multiple exercises. There were 2 main options in achieving this.

First was to have the code of the current exercise automatically copied to user clipboards when clicking the `"Run Code"` button.

Second was to have the code of the current exercise automatically copied and pasted to the next exercise chunk after some simplified action.

After a swift response from user grrrck on this [RStudio Community Thread](https://community.rstudio.com/t/learnr-clipboard-extension/107812), a clearer direction was laid out. I implemented the answer suggested but Preceptor pointed out that a lot of copy/pasting from the tutorial-maker's side was required. The problem then was how to minimize the amount of code needed to be repeatedly copied/pasted. Since the answer suggested used actionButtons from Shiny which had little room for customization, we thought there wasn't a way to know which exercise was locally close to the button.

Therefore, I created a second version that was a bit "brute-force" by having arguments for the code chunks that had the actionButtons, then reading the file itself to find those arguments and extract the labels of the exercise. But that was still a lot of code to copy/paste and God forbid someone wants to insert a new exercise at the beginning because you'll have to manually change so many exercise names that come after.

Here I realized that I don't have to use Shiny's actionButtons and can just use normal html buttons with trigger events that call a javascript function, which can directly communicate with the Shiny server, thus finally reaching the current version. Now no more exercise-specific information needs to be specified, only the exact same button for each exercise.

**Possible Improvements:**
Personally, I think the current solution is very close to the ideal solution. The only downsides being that 1) tutorial makers still have to include something in the exercises and 2) the button would look much better on the toolbar section of the exercise, next to `"Start Over"` and where the "hint" would be.

However, the possibility of automatically copying code to clipboard when clicking the `"Run Code"` button has yet been explored and could offer a better solution.

### Other Items

* To create a hint based on custom markdown content simply add a `<div>` tag with an id attribute that marks it as hint for your exercise. Like this:

````markdown
`r ''`<div id="filter-hint">
**Hint:** You may want to use the dplyr `filter` function.
</div>
````

Maybe this is how we should do all hints, so as to avoid the compile error issue.

* Combine the tutorial questions and the book together someday! Look to this for inspiration.

https://github.com/tinystats/teacups-giraffes-and-statistics



Only create permanent objects in tutorials if you have to. But do it when you have to! 

