---
title: "Mechanisms"
tutorial:
  id: "mechanisms"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "ADD DESCRIPTION"
---

```{r setup, include = FALSE}
library(learnr)
library(all.primer.tutorials)
library(tidyverse)
library(primer.data)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

```{r copy-code-chunk, child = system.file("child_documents/copy_button.Rmd", package = "tutorial.helpers")}
```

```{r info-section, child = system.file("child_documents/info_section.Rmd", package = "tutorial.helpers")}
```

<!-- What happens when our assumptions are violated? Of course, we have not really talked yet about assumptions in a rigorous way, but maybe this is where we do? Consider the assignment mechanism and the sampling mechanism. Both are examples of the broader category of missing data mechanisms. Why is our Preceptor Table missing items, both whole rows and, sometimes, just some columns? What assumptions do we need to make to fill in those missing values. -->

<!-- This sets the stage for all the discussions about unrepresentativeness which follow in later chapters. -->

<!-- Data is not representative if there is a correlation between missingness --- the probability that a data row is not available --- and other stuff, especially the outcome variable. Need to go through the different ways that data can be missing. If the correlation is between missing and unobserved potential outcomes, then you are screwed. If it is between missingness and observed outcomes, then there are ways to fix, but it is hard. If it is between missingness and right-hand side variables, you should worry. If it is, officially, between missingness -->


<!-- Perfect doctor example? Shows why the recommended approach in Chapter 4 only works with random assignment. -->

<!-- CHECKLIST BEFORE STARTING: -->
<!-- * Load necessary libraries for tutorial in the first code chunk -->
<!-- * Edit yaml at the START OF THIS FILE -->
<!-- * Review: https://ppbds.github.io/primer.tutorials/articles/instructions.html -->


<!-- ## First section (use sentence case) -->
<!-- ### -->

```{r download-answers, child = system.file("child_documents/download_answers.Rmd", package = "tutorial.helpers")}
```
