---
title: "One Parameter: Polling"
author: Ryan Southward
tutorial:
  id: "one-parameter-polling"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "Use polling data from the 2012 election to answer questions about support for President Obama."
---

```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(primer.data)
library(rstanarm)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 

obama_data <- tibble(approve = c(rep(1, round(.58*2087)), rep(0, round(.39*2087))))

fit_1 <- stan_glm(data = obama_data,
                    refresh = 0,
                    seed = 2012, 
                    family = binomial,
                    formula = approve ~ 1) 

ob_ppd <- posterior_epred(fit_1, 
                          newdata = tibble(constant = 1)) %>%
  as_tibble() %>%
  rename(approval = `1`) 
```

```{r copy-code-chunk, child = "../../child_documents/copy_button.Rmd"}

```

```{r info-section, child = "../../child_documents/info_section.Rmd"}

```


<!-- Do 053-probability-rolling-dice. This is a good template. What are the key lessons we want to teach? One lesson per Section, more or less. One graphic per lesson, more or less. -->

<!-- 1) Interpret the posterior from a standard survey. -->

<!-- 2) When comparing two surveys of different sizes, the uncertainty about a population parameter like \rho is much larger in the smaller survey --- assuming that the smaller survey is not too large. -->

<!-- 3) When comparing two surveys of different sizes, inferences about future samples differ much less than you might expect. Main difference is that smaller survey predicts that outlier events are (very slightly!) more like likely.  -->

<!-- 4) From your write up. -->


## Introduction
###

<!-- Two to four sentence about the main topics covered in this tutorial. Why are we here? What will students get out of giving you 90 minutes of their lives? How does this tutorial connect to previous tutorials? -->

<!-- Each Section will be introduced with a one or two sentence summary of what the point of that Section is. What do we want students to remember? The Introduction and the Conclusion are 4 sentence paragraphs which are a summary of the Sections' summaries. -->


## Obama approval
###

## Study

###

## Posterior

###

Let's create the posterior distribution for the proportion $\rho$ of U.S 18-29 year olds who approved of President Obama in 2009,  


<!-- RS: In two different rooms of the same size, one filled with all American adults, and one filled with just 18-29 year olds, what is the probability that the rooms will have a different number of people who approve of Obama? -->


### Exercise 1



```{r posterior-1, exercise = TRUE}

```

```{r posterior-1-hint-1, eval = FALSE}

```

###

## Questions

###


<!-- Two to four sentences which bring the lessons of the tutorial together for the student. What do they know now that they did not know before? How does this tutorial connect to future tutorials? OK if this is very similar to the Introduction. You made a promise as to what they would learn. You (I hope!) kept that promise.-->

<!-- In this case, the Summary will repeat the main lessons, which are just the simple lessons of each Section combined. But it can do so more quickly than was done in the Introduction since, one hopes, students now understand those lessons. -->

```{r download-answers, child = "../../child_documents/download_answers.Rmd"}

```
