---
title: "Visualization: Case Studies"
tutorial:
  id: "visualization-case_studies"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "Maps and other case studies."
---


```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(primer.data)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

```{r copy-code-chunk, child = "../../child_documents/copy_button.Rmd"}
```

```{r info-section, child = "../../child_documents/info_section.Rmd"}
```


<!-- Not sure yet what we should do here. Maybe maps, following the maps appendix closely? Maybe a series of plots, each requiring 10 or so questions, often using new packages. -->

<!-- Maybe use 5 or 6 of these plots: -->
<!-- https://www.cedricscherer.com/slides/RLadiesTunis-2021-favorite-ggplot-extensions.pdf -->
<!-- Although we may need to simplify them so that they don't require 30 Exercises. You will often need to find the code elsewhere, often at the Github repo for the package. Example: https://github.com/davidsjoberg/ggstream. I think the movie type graphic works well. -->


```{r download-answers, child = "../../child_documents/download_answers.Rmd"}
```
