---
title: "Gathering-Data"
tutorial:
  id: "02-gathering-data"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "Chapter 2 Gathering Data"
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```



### Exercise 1

Let’s use the `read_csv()` and set `file` to `test_1.csv`.  

```{r readcsv-setup}
writeLines("a,b,c\n1,2,3", con = "test_1.csv")
```


```{r readcsv, exercise = TRUE}

```


### Exercise 2

Let’s now use the `read_csv()` and set `file` to `test_2.csv`. You will see that R gives us a warning. That is because there is a comment "Junk at top" at the top of our tibble.

```{r readcsv-2-setup}
writeLines("#junk on top\na,b,c\n1,2,3", con = "test_2.csv")
```


```{r readcsv-2, exercise = TRUE}

```

### Exercise 3

We can resolve the warning above using the `skip` argument. Copy and paste your code from above and set the argument `skip` to 1 


```{r readcsv-3-setup}
writeLines("#junk on top\na,b,c\n1,2,3", con = "test_2.csv")
```

```{r readcsv-3, exercise = TRUE}

```
