---
title: "Probability B"
tutorial:
  id: "probability-b"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "Chapter 5 tutorial Part B"
---

```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(primer.data)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 

```

```{r copy-code-chunk, child = "../../child_documents/copy_button.Rmd"}
```

```{r info-section, child = "../../child_documents/info_section.Rmd"}
```


<!-- First examples show how as sample size increases, you get a distribution which is more and more similar to the mathematical. Do this with rolling two dice. Final plot is 3 x 2 matrix of plots, each an empirical distribution, but with increase N.  Use map functions and list-columns, maybe. -->

<!-- Do tutorial for chapter 6 first! -->

<!-- tibble with one column N which is number of samples, one column result,  -->

<!-- N   result -->
<!-- 10    3 -->
<!-- 10    7 -->
<!-- 10    7 -->
<!-- 10    4 -->
<!-- .. -->
<!-- 20 -->
<!-- 20 -->
<!-- 20 -->
<!-- twenty rows -->
<!-- ... -->
<!-- 100 -->
<!-- 100 -->
<!-- one hundred rows -->

<!-- geom_histogram(aes(x = result)) and facet_wrap(~ N) -->



## Roulette (outside bet)













```{r download-answers, child = "../../child_documents/download_answers.Rmd"}
```



