---
title: "Distributions"
tutorial:
  id: "distributions"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "ADD DESCRIPTION"
---


```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(primer.data)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

```{r copy-code-chunk, child = "../../child_documents/copy_button.Rmd"}
```

```{r info-section, child = "../../child_documents/info_section.Rmd"}
```

<!-- Add to chapter 5 a tutorial whose sole focus is distributions. First part of this is going slowly through the process by which counts can be turned into percentages. Do this in, at least, five ways. First, with geom_bar() which (I think) does the counting for us. Second, with geom_col(), in which we need to create the counts ourselves. Third with geom_histogram(). Fourth then maybe create a histogram by hand, using cut() and then counting up the elements in each range. -->

<!-- Put the Appendix-distribution questions somewhere here. -->

<!-- Maybe have a section explaining how the distribution of the error term is what motivates the selection of the appropriate family argument in stan_glm(). -->

<!-- CHECKLIST BEFORE STARTING: -->
<!-- * Load necessary libraries for tutorial in the first code chunk -->
<!-- * Edit yaml at the START OF THIS FILE -->
<!-- * Review: https://ppbds.github.io/primer.tutorials/articles/instructions.html -->


<!-- ## First section (use sentence case) -->
<!-- ### -->

```{r download-answers, child = "../../child_documents/download_answers.Rmd"}
```
