---
title: "Getting Help"
tutorial:
  id: "getting-help"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "ADD DESCRIPTION"
---


```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(primer.data)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

```{r copy-code-chunk, child = "../../child_documents/copy_button.Rmd"}
```

```{r info-section, child = "../../child_documents/info_section.Rmd"}
```

<!-- * A "help" tutorial which covers all aspects of finding help. Start with the reprex package. Make the reprex in a .R file and show that file as you make progress. Perhaps make a bad reprex first, one which leaves out the library(tidyverse) calls. Also the R package which searches all packages on CRAN. https://www.zuckarelli.de/packagefinder/tutorial.html (Maybe add something about searching Github to help, which I don't know how to do well.) -->

<!-- This is nice: https://themockup.blog/posts/2021-07-28-reminder-to-test-with-a-reprex/ -->

<!-- More knowledge to drop: -->

<!-- https://reprex.tidyverse.org/index.html -->
<!-- https://www.youtube.com/watch?v=5gqksthQ0cM -->
<!-- https://reprex.tidyverse.org/articles/articles/learn-reprex.html -->

<!-- https://www.r-project.org/help.html -->



<!-- CHECKLIST BEFORE STARTING: -->
<!-- * Load necessary libraries for tutorial in the first code chunk -->
<!-- * Edit yaml at the START OF THIS FILE -->
<!-- * Review: https://ppbds.github.io/primer.tutorials/articles/instructions.html -->


<!-- ## First section (use sentence case) -->
<!-- ### -->

```{r download-answers, child = "../../child_documents/download_answers.Rmd"}
```
