---
title: "Workflow"
author: Anmay Gupta
tutorial:
  id: "workflow"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "Tips and tricks for working in RStudio"
---


```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(primer.data)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

```{r copy-code-chunk, child = "../../child_documents/copy_button.Rmd"}
```

```{r info-section, child = "../../child_documents/info_section.Rmd"}
```

<!-- All current features:

We could do "projects," which would cover more ground in terms of putting together projects with lots of files. 

Cover the **here** package. And maybe other topics from https://rstats.wtf/.  

Should certainly cover the .Rprofile file. 

Have examples of changing it, adding a print statement, restarting R, seeing the print statement (and copy/pasting what you see as proof). 

Always using the **usethis** commands.

Perhaps also discuss the .Renviron file. 

Maybe some (fake?) examples of issues associated with (not) using :: to identify the package from which you want the function to come. 

Perhaps we save gists for this tutorial. Don't want RStudio and friends to be too long. 

Maybe also discuss base R versus tidyverse so that students are not confused when they see base R. 

Have a tutorial for this. 

Maybe there is a week 4 tutorial which covers all the random R topics we failed to cover before. That's this one! 

What to do with PDF and tinytex? This all seemed to work very easily. Maybe just install and then issue packageVersion("tinytex")? 

Another topic: The Style Guide, and key components thereof. Not sure how to teach that here ... 

This link is hilarious and great for default R: https://www.tidyverse.org/blog/2017/12/workflow-vs-script/ 

https://speakerdeck.com/jennybc/zen-and-the-art-of-workflow-maintenance?slide=62

Knowledge to drop:
R sets Renviron vars first, then runs RProfile.site for the OS, then .Rprofile for the user. Finally, it loads the .RData (blankslate removed this), then loads the default packages in .First(), loads the history, and finally everything else.
So the end, it's Env vars -> OS Rprofile -> User RProfile -> Load .RData -> Load default packages -> Load History -> Your Scripts.

Workflows should be structured like this:
Import data -> Tidy data -> Transform data -> Visualize -> Model -> Communicate
                                    ^-----------------------|

RTools install and stuff: https://cran.r-project.org/bin/windows/Rtools/

Maybe information about debugging? This might be too advanced: https://www.atorusresearch.com/when-browser-dont-cut-it/. 
https://rstats.wtf/debugging-r-code.html

This is nice: https://themockup.blog/posts/2021-07-28-reminder-to-test-with-a-reprex/ -->

<!-- Plan for this tutorial: 

Have them fork a buggy repo. 
 - I really want to show them branches because it's an integral part of Git and is brought up in almost every Git tutorial. The majority of Git and GitHub is in dealing with branches for different people and using them to contribute. Not teaching branches is like not teaching them how to contribute to a GitHub project.

Clean up

Debug the R Script using browser() and breakpoints. 

Properly style and format the R Markdown file following the style guide.

They then create a gist and integrate that into their R Markdown file using the HTML link or some similar method. 

And finally, they publish the R Markdown to a PDF using LaTeX and tinytex.

-->

## Forking

<!-- AG: I haven't actually put any code in the forked repo yet. -->

In this tutorial, we'll be dealing with the workflow

## File cleanup

## Debugging

## Styling

## Gists

## Publishing

```{r download-answers, child = "../../child_documents/download_answers.Rmd"}
```
