<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Cardinal Virtues • primer.tutorials</title>
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="cardinal_virtues_files/libs/quarto-html/popper.min.js"></script><script src="cardinal_virtues_files/libs/quarto-html/tippy.umd.min.js"></script><link href="cardinal_virtues_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cardinal_virtues_files/libs/quarto-html/light-border.css" rel="stylesheet">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Cardinal Virtues">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">primer.tutorials</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">1.3.9010</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles">
<li><a class="dropdown-item" href="../articles/cardinal_virtues.html">Cardinal Virtues</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/ppbds/primer.tutorials/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">

      <h1>Cardinal Virtues</h1>

      <p class="author">David Kane</p>
      <p class="date">2025-06-19</p>

      <small class="dont-index">Source: <a href="https://github.com/ppbds/primer.tutorials/blob/master/vignettes/cardinal_virtues.qmd" class="external-link"><code>vignettes/cardinal_virtues.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <!-- When starting a new chapter, copy/paste this:

## Wisdom

### Preceptor Table

*Units*:

*Outcome*:

*Causal or predictive model*:

*Covariates*:

*Treatment*:

*Moment in Time*:

### EDA

### Validity

## Justice

### Population Table

### Stability

### Representativeness

### Unconfoundedness

## Courage

### Models

### Tests

### Data Generating Mechanism

## Temperance

### Questions and Answers

### Humility

--><p>In the spirit of transparency, here are the guidelines which we provide to colleagues updating chapters in the <a href="https://ppbds.github.io/primer/" class="external-link"><em>Primer</em></a> and writing tutorials in this package. This is how we think data science ought to be taught. It is also, perhaps unsurprisingly, how we think data science ought to be done, at least at this introductory level. Key concepts are bolded when they are first introduced.</p>
<section class="level2"><h2 id="introduction">Introduction<a class="anchor" aria-label="anchor" href="#introduction"></a>
</h2>
<p>The world confronts us. Make decisions we must.</p>
<p>Who am I and what problem am I trying to solve?</p>
<ul>
<li><p>Imagine that you are running for Governor of Texas in the next election. You have a campaign budget. Your goal is to win the election. Winning the election involves convincing people to vote for you <em>and</em> getting your supporters to vote. Should you send postcards to registered voters likely to vote for you? What should those postcards say?</p></li>
<li><p>Imagine that you are in charge of ordering uniforms for bootcamp recruits in the Marine Corps for next year. There are many factors to consider: the cost of different designs, the number of male and female recruits, the distributions of heights and weights, and so on. What should you order?</p></li>
<li><p>Imagine that you are a historian trying to understand the 1992 US Presidential election. Who voted? Who did they vote for? Why did they vote as they did? What might have led them to vote differently?</p></li>
</ul>
<p>Of course, we are never going to be able to answer all those questions. They are much too hard! But we should be able to make some progress, to learn something about the world which will help us to make better decisions.</p>
</section><section class="level2"><h2 id="question">Question<a class="anchor" aria-label="anchor" href="#question"></a>
</h2>
<p>Once we have motivated the issue by imagining ourselves as a specific person facing a collection of decisions, we can move onto a broad question which, we hope, will be relevant. Examples:</p>
<blockquote>
<p><em>How do voters respond to postcards?</em></p>
</blockquote>
<blockquote>
<p><em>How does height vary by sex?</em></p>
</blockquote>
<blockquote>
<p><em>What explains individual voting decisions in the 1992 US Presidential election?</em></p>
</blockquote>
<p>In order to make progress, you will then drill down to a more specific question, one which specifies variables for which we actually have data. The key refinement at this stage is that we have gone from general terms to a variable with a specific definition, available in a data set to which we have access. Examples:</p>
<blockquote>
<p><em>What is the causal effect on voting behavior of receiving a postcard which specifies which of your neighbors voted in the last election?</em></p>
</blockquote>
<blockquote>
<p><em>What is the height of young men and women in the US?</em></p>
</blockquote>
<blockquote>
<p><em>How did the likelihood of voting for Bush/Clinton/Perot in the 1992 US Presidential election vary by sex?</em></p>
</blockquote>
<p>With specific variables, we can construct a statistical model. That statistical model can be used to answer all sorts of questions.</p>
<p>Of course, our data must contain the variables which allow us to answer the question, otherwise we need a new question.</p>
<p>Specifics help you to fix ideas as you start to work on a project. Just because you start looking for this number does not mean that we can’t consider other questions.</p>
<p>Your interim goal is to provide an answer to the specific question, along with your uncertainty about that answer. To calculate these, you will create a series of models, the final version of which we refer to as the data generating mechanism (DGM). Once you have the DGM, you can not only answer that specific question. You can also answer lots of similar questions, thereby allowing you to discuss the broader topic in much more detail.</p>
<p>Each chapter features all the same sections and sub-sections as we use below. That is, there are three sub-sections to Wisdom, four sub-sections for Justice, three for Courage and two for Temperance.</p>
<p><strong>Quantity of Interest</strong> is the number that you want to estimate. It is the answer to a specific question. You will almost always calculate a posterior probability distribution for your Quantity of Interest since, in the real world, you will never know your QoI precisely. Exploring the general question will require the calculation of many Quantities of Interest.</p>
<p>Once we have our specific question, we can start with the Cardinal Virtues. Each section begins with a one sentence summary about the component steps of the relevant virtue. These will, obviously, be highly similar from chapter to chapter. But that is OK! We want to reinforce the steps in the path over and over again.</p>
<p>No battle plan survives first contact with the enemy intact. The same applies to questions and the data we use to answer them. Our questions evolve as our analysis continues. Ultimately, we can only answer some questions with the data we have. Those questions may be close to the ones with which we started, but they will rarely be identical.</p>
</section><section class="level2"><h2 id="wisdom">Wisdom<a class="anchor" aria-label="anchor" href="#wisdom"></a>
</h2>
<blockquote>
<p>Wisdom requires the creation of a Preceptor Table, an examination of our data, and a determination, using the concept of validity, as to whether or not we can (reasonably!) assume that the two come from the same population.</p>
</blockquote>
<p><strong>Wisdom</strong> is the first <a href="https://en.wikipedia.org/wiki/Cardinal_virtues" class="external-link">Cardinal Virtue</a> in data science. Begin with the quantity of interest. Is that QoI a causal effect or simply a forecast? Which units and outcomes does it imply? What Preceptor Table would allow you to calculate your QoI easily? Perform an exploratory data analysis (EDA) on the data you have. Is it <em>valid</em> to consider the data you have and the (theoretical) data from the Preceptor Table to have arisen out of the same population? If so, you may continue. If not, your attempt to estimate your QoI ends now.</p>
<section class="level3"><h3 id="preceptor-table">Preceptor Table<a class="anchor" aria-label="anchor" href="#preceptor-table"></a>
</h3>
<blockquote>
<p>A Preceptor Table is the smallest possible table with rows and columns such that, if there is no missing data, our question is easy to answer.</p>
</blockquote>
<p><strong>Predictive Models and Causal Models</strong> are different because predictive models have only one outcome column. Causal models have more than one (potential) outcome column because we need more than one potential outcome in order to estimate a <em>causal effect</em>. The first step in a data science problem is to determine if your QoI requires a causal or a predictive model.</p>
<p>If you don’t care what Joe would have done in a counter-factual world in which he got a different treatment, if all you care about is predicting what Joe does <em>given the treatment he received</em>, then you just need a predictive model.</p>
<p><strong>Units</strong> are determined by the original question, which also determines the QoI. They are the <strong>rows</strong>, both in the <em>Preceptor Table</em> and in the data.</p>
<p><strong>Variables</strong> is the general term for the <strong>columns</strong> in both the Preceptor Table and the data. In fact, the term is even more general since it may refer to data vectors which we would like to have in order to answer the question but which are, sadly, not available in the data. The columns in the data are a subset of all the variables in which we might be interested.</p>
<p><strong>The outcome</strong> is the most important variable. It is determined by the question/QoI. By definition, it must be present in both the data and the Preceptor Table. Different problems might be answered with the same data set, with different variables playing the role of the outcome in each case.</p>
<p><strong>Covariates</strong> is the general term for all the variables which are not the <strong>outcome</strong>. As with <strong>variables</strong>, there are three different contexts in which we might use the term covariates. First, covariates are all the variables which might have some connection with our outcome, even if they are not included in the data. Second, covariates are all the variables in the data other than the outcome. Third, covariates can refer to just the subset of the variables in the data which we actually use in our model. The second usage is, obviously, a subset of the first, and the third usage is a subset of the second.</p>
<p><strong>Units</strong>, <strong>outcomes</strong> and <strong>covariates</strong> are important parts of every data science model. Causal, but not predictive, models also include at least one <strong>treatment</strong>, which is just a covariate which we can, at least in theory, manipulate. The QoI determines the units and outcomes for your model.</p>
<p><strong>Potential Outcome</strong> is the outcome for an individual under a specified treatment. A <em>potential outcome</em> is just a regular outcome in the case of a causal model. In a predictive model, we just have an outcome. It is just another variable, the one that, in the context of this problem, we are interested in explaining/modeling/predicting. In a causal model, on the other hand, there are at least two outcomes: the outcome which happens if the unit gets the treatment and the outcome which happens if that same unit gets the control. We refer to both of these outcomes as <em>potential outcomes</em>.</p>
<p><strong>Causal Effect</strong> is the difference between two potential outcomes.</p>
<p><a href="https://en.wikipedia.org/wiki/Rubin_causal_model" class="external-link"><strong>Rubin Causal Model</strong></a> is an approach to the statistical analysis of cause and effect based on the framework of potential outcomes.</p>
<p>To create the Preceptor Table, we answer a series of questions:</p>
<ul>
<li>C<em>ausal or predictive?</em> Look for verbs like “cause” or “affect” or “influence.” Look for a question which implies a comparison, <em>for a single individual unit</em>, between two states of the world, one in which the unit receives treatment <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>X</mi><annotation encoding="application/x-tex">X</annotation></semantics></math> and one in which the unit gets treatment <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>Y</mi><annotation encoding="application/x-tex">Y</annotation></semantics></math>. Look for a discussion of something which we can <em>manipulate</em>. Remember the motto: <em>No causation without manipulation</em>. We look to see if the question seeks to compare two potential outcomes <em>within the same unit</em>, rather than the same outcome between two different units.</li>
</ul>
<p>If none of this is present, use a predictive model. If all you need to know to answer the question is the outcome under one value of the treatment, then the model is predictive. In that case, the treatment is not truly a “treatment.” It is just a covariate. Example: What is the <code>att_end</code> for all women if they were to get the treatment? This is a predictive question, not a causal one, because we do not need to know the outcome under treatment <em>and</em> under control for any individual woman.</p>
<ul>
<li>
<em>What is the moment in time to which the question refers?</em> Every question refers to a moment in time, even if that moment stretches a bit. The set of adults <em>today</em> is different from the set 10 years ago, or even yesterday. We need to <em>refine</em> the original question. Assume that we are referring to July 1, 2020 even though, in most cases, people are interested in <em>now</em>. We have changed the original question from:</li>
</ul>
<blockquote>
<p>What proportion of people who make $100,000 are liberal?</p>
</blockquote>
<p>to</p>
<blockquote>
<p>On July 1, 2020, what proportion of people who made $100,000 were liberal?</p>
</blockquote>
<ul>
<li>
<em>What are the units?</em> The question often makes this fairly clear, at least in terms of what each row corresponds to, whether it be individuals, classrooms, countries, or whatever. But, questions often fail to make clear the total number of the rows. Our example question above does not specify the relevant population. Is it about all the people in the world? All the adults? All the adults in the United States? The purpose of this paragraph is to <em>refine</em> the question, to make it more specific. Assume that we are interested in all the adults in Chicago. Our question now is:</li>
</ul>
<blockquote>
<p>On July 1, 2020, what proportion of the adults in Chicago who made $100,000 were liberal?</p>
</blockquote>
<p>This back-and-forth between the question and the analysis is a standard part of data science. We rarely answer the exact question we started with, especially because that question is never specific enough to answer without further qualifications. Furthermore, the data we have may not allow us to answer that question, but it may be enough to answer a related question. Is that good enough for the boss/client/colleague who asked the original question? Maybe? You won’t know until you ask.</p>
<p>Our job as data scientists is not to simply answer the question we have been asked, but to help the questioner determine a question which can be answered with the data we have, a question which helps them to make the decisions which they face.</p>
<ul>
<li><p><em>What are the outcomes?</em> (If the model is causal, then there must be at least two potential outcomes. If you can’t figure them out, then the model is probably predictive.) If the model is predictive, then there is only one outcome. This paragraph does more than just name the relevant variable. It also starts the discussion about how exactly we might measure this variable. We consider both the underlying concept, “liberal,” and the process by which we might operationalize the concept. Perhaps we are using a written survey with a YES/NO answer. Perhaps it is an in-person interview with a 1-7 Likert scale, in which answers of 1 or 2 are coded, by us, as “liberal.” The details may or may not matter, but we at least need to discuss the issue.</p></li>
<li><p><em>What are the covariates?</em> Discussing covariates in the context of the Preceptor Table is different than discussing covariates in the context of the data. Recall that the Preceptor Table is the smallest possible table, so we don’t need to include every relevant variable. We only need to discuss variables that are necessary to answer the question.</p></li>
<li><p><em>What are the treatments, if any?</em> (There are no “treatments” in predictive models. There are only covariates.) A treatment is a covariate which, at least in theory, we can manipulate and the manipulation of which is necessary to answer our question.</p></li>
</ul>
<p>With all the above, create the Preceptor Table. In this case, our Preceptor Table includes <code>N</code> rows, one for every adult in Chicago on July 1, 2020. It includes two columns: the outcome (<code>liberal</code>) and a single covariate (<code>income</code>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="jbqdorxzll" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#jbqdorxzll table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#jbqdorxzll thead, #jbqdorxzll tbody, #jbqdorxzll tfoot, #jbqdorxzll tr, #jbqdorxzll td, #jbqdorxzll th {
  border-style: none;
}

#jbqdorxzll p {
  margin: 0;
  padding: 0;
}

#jbqdorxzll .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jbqdorxzll .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#jbqdorxzll .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jbqdorxzll .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jbqdorxzll .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jbqdorxzll .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jbqdorxzll .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jbqdorxzll .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jbqdorxzll .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jbqdorxzll .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jbqdorxzll .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jbqdorxzll .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jbqdorxzll .gt_spanner_row {
  border-bottom-style: hidden;
}

#jbqdorxzll .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#jbqdorxzll .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jbqdorxzll .gt_from_md > :first-child {
  margin-top: 0;
}

#jbqdorxzll .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jbqdorxzll .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jbqdorxzll .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#jbqdorxzll .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#jbqdorxzll .gt_row_group_first td {
  border-top-width: 2px;
}

#jbqdorxzll .gt_row_group_first th {
  border-top-width: 2px;
}

#jbqdorxzll .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jbqdorxzll .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#jbqdorxzll .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#jbqdorxzll .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jbqdorxzll .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jbqdorxzll .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jbqdorxzll .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#jbqdorxzll .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jbqdorxzll .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jbqdorxzll .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jbqdorxzll .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jbqdorxzll .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jbqdorxzll .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jbqdorxzll .gt_left {
  text-align: left;
}

#jbqdorxzll .gt_center {
  text-align: center;
}

#jbqdorxzll .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jbqdorxzll .gt_font_normal {
  font-weight: normal;
}

#jbqdorxzll .gt_font_bold {
  font-weight: bold;
}

#jbqdorxzll .gt_font_italic {
  font-style: italic;
}

#jbqdorxzll .gt_super {
  font-size: 65%;
}

#jbqdorxzll .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#jbqdorxzll .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#jbqdorxzll .gt_indent_1 {
  text-indent: 5px;
}

#jbqdorxzll .gt_indent_2 {
  text-indent: 10px;
}

#jbqdorxzll .gt_indent_3 {
  text-indent: 15px;
}

#jbqdorxzll .gt_indent_4 {
  text-indent: 20px;
}

#jbqdorxzll .gt_indent_5 {
  text-indent: 25px;
}

#jbqdorxzll .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#jbqdorxzll div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="table gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="gt_heading header">
<th colspan="3" class="gt_heading gt_title gt_font_normal gt_bottom_border">Preceptor Table</th>
</tr>
<tr class="gt_col_headings gt_spanner_row even">
<th rowspan="2" id="ID" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" style="text-align: left; font-size: large; vertical-align: middle;" scope="col">ID</th>
<th id="Outcome" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="col"><div class="gt_column_spanner">
Outcome
</div></th>
<th id="Covariate" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="col"><div class="gt_column_spanner">
Covariate
</div></th>
</tr>
<tr class="gt_col_headings header">
<th id="liberal" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Liberal</th>
<th id="income" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Income</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="ID" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">1</td>
<td class="gt_row gt_center" headers="liberal">0</td>
<td class="gt_row gt_center" headers="income">150000</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="ID" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">2</td>
<td class="gt_row gt_center" headers="liberal">0</td>
<td class="gt_row gt_center" headers="income">50000</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="ID" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">…</td>
<td class="gt_row gt_center" headers="liberal">…</td>
<td class="gt_row gt_center" headers="income">…</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="ID" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">10</td>
<td class="gt_row gt_center" headers="liberal">1</td>
<td class="gt_row gt_center" headers="income">65000</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="ID" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">11</td>
<td class="gt_row gt_center" headers="liberal">1</td>
<td class="gt_row gt_center" headers="income">35000</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="ID" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">…</td>
<td class="gt_row gt_center" headers="liberal">…</td>
<td class="gt_row gt_center" headers="income">…</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="ID" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">N</td>
<td class="gt_row gt_center" headers="liberal">1</td>
<td class="gt_row gt_center" headers="income">78000</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>If we have the Preceptor Table, with no missing data, then it is trivial to calculate the percentage of adults (who make more than $100,000) who are liberal.</p>
<p>The Preceptor Table is, really, not the smallest possible table which solved your problem. That would be a table with a single cell containing the quantity of interest! This is, obviously, stupid. The Preceptor Table is the smallest possible table, with rows corresponding to units about which we have some information, which allows us to answer the question.</p>
</section><section class="level3"><h3 id="eda">EDA<a class="anchor" aria-label="anchor" href="#eda"></a>
</h3>
<blockquote>
<p>You can never look at the data too much. – Mark Engerman</p>
</blockquote>
<p>There is always a short section devoted to exploratory data analysis. Each EDA will include at least one textual look at the data, usually using <code><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary()</a></code>, but with <code>skim()</code>, <code>glimpse()</code>, <code><a href="https://rdrr.io/r/base/print.html" class="external-link">print()</a></code> and <code>slice_sample()</code> also available. It will also include at least one graphic, almost always with the outcome variable on the y-axis and one of the covariates on the x-axis. The data set will often include columns and rows which are irrelevant to the question. Those columns and rows are removed, creating a tibble which will be used in the Courage section. The name of that tibble will often be something convenient like <code>ch_7</code>.</p>
<p>It also makes sense to include some discussion about where this data comes from. What are the definitions of the variables? Who chose the sample? Where is the documentation? This sort of background sets the stage for examining validity.</p>
</section><section class="level3"><h3 id="validity">Validity<a class="anchor" aria-label="anchor" href="#validity"></a>
</h3>
<blockquote>
<p>Validity is the consistency, or lack thereof, in the columns of your data set and the corresponding columns in your Preceptor Table.</p>
</blockquote>
<p>In order to consider the two data sets to be drawn from the same population, the columns from one must have a <em>valid correspondence</em> with the columns in the other. Validity, if true (or at least reasonable), allows us to construct the <em>Population Table</em>, which is the first step in Justice.</p>
<p>Validity discussions always have one (short) paragraph about each relevant variable (the outcome and any relevant covariates), with examples of why validity might <em>not</em> hold. Validity discussion finishes with a brief discussion along the lines of: “Despite these concerns, we will assume that validity does hold.”</p>
<p>These section can be longer of course, depending on how many details you discussed during the EDA. The central point is that we have two (potentially!) completely different things: the Preceptor Table and the data. <em>Just because two columns have the same name does not mean that they are the same thing.</em> Indeed, they will often be quite different! But because we control the Preceptor Table and, to a lesser extent, the original question, we can adjust those variables to be “closer” to the data that we actually have. This is another example of the iterative nature of data science. If the data is not close enough to the question, then we check with our boss/colleague/customer to see if we can modify the question in order to make the match between the data and the Preceptor Table close enough for validity to hold.</p>
<p>We conclude the Wisdom section by summarizing how we hope to use the data we have to answer the question we started with. Example:</p>
<blockquote>
<p>Using data from a 2012 survey of Boston-area commuters, we seek to understand the relationship between income and political ideology in Chicago and similar cities in 2020. In particular, what percentage of individuals who make more than $100,000 per year are liberal?</p>
</blockquote>
<p>Note how the specific question has morphed into a general examination of the “relationship” between income and political ideology. In order to answer any specific question, we always have to examine a more general relationship. We always have to build a model. We can then use this model to answer both the question we started with as well as other related questions.</p>
<p>By thinking hard about the original question and the data, we have come up with a question which <em>may</em> be possible to answer with the data we have. Note that each Cardinal Virtue section finishes with a sentence or two summarizing what you have learned. Those sentences are combined at the end of the analysis. One of the key products of a data science project is a paragraph which summarizes the key conclusions.</p>
</section></section><section class="level2"><h2 id="justice">Justice<a class="anchor" aria-label="anchor" href="#justice"></a>
</h2>
<blockquote>
<p>Justice concerns four topics: the Population Table, stability, representativeness, and unconfoundedness.</p>
</blockquote>
<p><strong>Justice</strong> is the second <a href="https://en.wikipedia.org/wiki/Cardinal_virtues" class="external-link">Cardinal Virtue</a> in data science. Justice starts with the Population Table – the data we want to have, the data which we actually have, and all the other data from that same population. Each row of the Population Table is defined by a unique unit/time combination. We explore three key issues. First, does the relationship among the variables demonstrate <em>stability</em>, meaning is the model stable across different time periods? Second, are the rows associated with the data and, separately, the rows associated with the Preceptor Table, <em>representative</em> of all the units from the population? Third, for causal models only, we consider <em>unconfoundedness</em>.</p>
<section class="level3"><h3 id="population-table">Population Table<a class="anchor" aria-label="anchor" href="#population-table"></a>
</h3>
<blockquote>
<p>The Population Table includes a row for each unit/time combination in the underlying population from which both the Preceptor Table and the data are drawn.</p>
</blockquote>
<p>The <strong>Population Table</strong> can be constructed if the validity assumption is (mostly) true. It includes all the rows from the Preceptor Table. It also includes the rows from the data set. It usually has other rows as well, rows which represent unit/time combinations from other parts of the population.</p>
<p>If validity holds, then we can create a Population Table.</p>
<div class="cell">
<div class="cell-output-display">
<div id="hlbpmwdqdg" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hlbpmwdqdg table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hlbpmwdqdg thead, #hlbpmwdqdg tbody, #hlbpmwdqdg tfoot, #hlbpmwdqdg tr, #hlbpmwdqdg td, #hlbpmwdqdg th {
  border-style: none;
}

#hlbpmwdqdg p {
  margin: 0;
  padding: 0;
}

#hlbpmwdqdg .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hlbpmwdqdg .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hlbpmwdqdg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hlbpmwdqdg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hlbpmwdqdg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hlbpmwdqdg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hlbpmwdqdg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hlbpmwdqdg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hlbpmwdqdg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hlbpmwdqdg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hlbpmwdqdg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hlbpmwdqdg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hlbpmwdqdg .gt_spanner_row {
  border-bottom-style: hidden;
}

#hlbpmwdqdg .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hlbpmwdqdg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hlbpmwdqdg .gt_from_md > :first-child {
  margin-top: 0;
}

#hlbpmwdqdg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hlbpmwdqdg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hlbpmwdqdg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hlbpmwdqdg .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hlbpmwdqdg .gt_row_group_first td {
  border-top-width: 2px;
}

#hlbpmwdqdg .gt_row_group_first th {
  border-top-width: 2px;
}

#hlbpmwdqdg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hlbpmwdqdg .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hlbpmwdqdg .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hlbpmwdqdg .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hlbpmwdqdg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hlbpmwdqdg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hlbpmwdqdg .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hlbpmwdqdg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hlbpmwdqdg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hlbpmwdqdg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hlbpmwdqdg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hlbpmwdqdg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hlbpmwdqdg .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hlbpmwdqdg .gt_left {
  text-align: left;
}

#hlbpmwdqdg .gt_center {
  text-align: center;
}

#hlbpmwdqdg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hlbpmwdqdg .gt_font_normal {
  font-weight: normal;
}

#hlbpmwdqdg .gt_font_bold {
  font-weight: bold;
}

#hlbpmwdqdg .gt_font_italic {
  font-style: italic;
}

#hlbpmwdqdg .gt_super {
  font-size: 65%;
}

#hlbpmwdqdg .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hlbpmwdqdg .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hlbpmwdqdg .gt_indent_1 {
  text-indent: 5px;
}

#hlbpmwdqdg .gt_indent_2 {
  text-indent: 10px;
}

#hlbpmwdqdg .gt_indent_3 {
  text-indent: 15px;
}

#hlbpmwdqdg .gt_indent_4 {
  text-indent: 20px;
}

#hlbpmwdqdg .gt_indent_5 {
  text-indent: 25px;
}

#hlbpmwdqdg .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#hlbpmwdqdg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="table gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="gt_heading header">
<th colspan="5" class="gt_heading gt_title gt_font_normal gt_bottom_border">Population Table</th>
</tr>
<tr class="gt_col_headings gt_spanner_row even">
<th rowspan="2" id="source" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Source</th>
<th rowspan="2" id="year" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Year</th>
<th id="Outcome" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="col"><div class="gt_column_spanner">
Outcome
</div></th>
<th colspan="2" id="Covariates" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
Covariates
</div></th>
</tr>
<tr class="gt_col_headings header">
<th id="income" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Income</th>
<th id="age" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Age</th>
<th id="city" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">City</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="source" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">…</td>
<td class="gt_row gt_center" headers="year">…</td>
<td class="gt_row gt_center" headers="income">…</td>
<td class="gt_row gt_center" headers="age">…</td>
<td class="gt_row gt_center" headers="city">…</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="source" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">Data</td>
<td class="gt_row gt_center" headers="year">2012</td>
<td class="gt_row gt_center" headers="income">150000</td>
<td class="gt_row gt_center" headers="age">43</td>
<td class="gt_row gt_center" headers="city">Boston</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="source" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">Data</td>
<td class="gt_row gt_center" headers="year">2012</td>
<td class="gt_row gt_center" headers="income">50000</td>
<td class="gt_row gt_center" headers="age">52</td>
<td class="gt_row gt_center" headers="city">Boston</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="source" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">…</td>
<td class="gt_row gt_center" headers="year">…</td>
<td class="gt_row gt_center" headers="income">…</td>
<td class="gt_row gt_center" headers="age">…</td>
<td class="gt_row gt_center" headers="city">…</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="source" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">…</td>
<td class="gt_row gt_center" headers="year">…</td>
<td class="gt_row gt_center" headers="income">…</td>
<td class="gt_row gt_center" headers="age">…</td>
<td class="gt_row gt_center" headers="city">…</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="source" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">Preceptor Table</td>
<td class="gt_row gt_center" headers="year">2020</td>
<td class="gt_row gt_center" headers="income">…</td>
<td class="gt_row gt_center" headers="age">…</td>
<td class="gt_row gt_center" headers="city">Chicago</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="source" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">Preceptor Table</td>
<td class="gt_row gt_center" headers="year">2020</td>
<td class="gt_row gt_center" headers="income">…</td>
<td class="gt_row gt_center" headers="age">…</td>
<td class="gt_row gt_center" headers="city">Chicago</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="source" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000">…</td>
<td class="gt_row gt_center" headers="year">…</td>
<td class="gt_row gt_center" headers="income">…</td>
<td class="gt_row gt_center" headers="age">…</td>
<td class="gt_row gt_center" headers="city">…</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ul>
<li><p>The “Source” column highlights that the Population Table includes three categories of rows: the data, the Preceptor Table, and the rest of the population, from which both the data and the Preceptor Table are drawn. The <code>...</code> indicates rows from the population which are not included in either the data or the Preceptor Table.</p></li>
<li><p>The “ID” column is implicit, and often not included. After all, it should be obvious that each row refers to a specific unit. If we don’t really care about the individual units, there is no need to label them.</p></li>
<li><p>There should always be a column, in this case “Year,” which indicates the moment in time at which the covariates were recorded. A given unit may appear in multiple rows, with each row providing the data at a different time. In this example, we will have a row for Sarah in 2012, when she was 43, and a row for Sarah in 2020, when she was 51, and so on. Note that Sarah might just be a member of the population, neither in the data we have nor in the Preceptor Table. Or she might be in one or the other. We are rarely concerned with any specific individual.</p></li>
<li><p>Each row in the Population Table represents a unique Unit/Time combination.</p></li>
<li><p>The “Outcome” column is the variable which we are trying to understand/explain/predict. There is always an outcome column, although it will often just be labelled with the variable name, as here with “Income.”</p></li>
<li><p>The “Covariates” are all the columns other than those already discussed.</p></li>
</ul></section><section class="level3"><h3 id="stability">Stability<a class="anchor" aria-label="anchor" href="#stability"></a>
</h3>
<blockquote>
<p>Stability means that the relationship between the columns in the Population Table is the same for three categories of rows: the data, the Preceptor Table, and the larger population from which both are drawn.</p>
</blockquote>
<p>If the assumption of stability holds, then the relationships between the columns in the Population Table is the same <em>across time</em>. First, the relationship among columns from the same moment in time as the data is the same as the relationship among columns for the entire table. Second, the relationship among columns from the same moment in time as the Preceptor Table is the same as the relationship among columns for the entire table.</p>
<p>Stability, if true, allows is us to go from the data to the population, and from the population to the Preceptor Table.</p>
<p>We discuss at least one example of why stability might <em>not</em> hold in this case. These examples are almost always connected to the passage of time. Whatever the relationship between political ideology and income that might have held in 2012, when we gathered our data, might not be true either before or afterwards. Provide specific speculations about what might have changed in the world.</p>
<p>Regardless of those concerns, we always conclude that, although the assumption of stability might not hold perfectly, the world is probably stable enough over this time period to make inference possible.</p>
<p><em>The longer the time period covered by the Preceptor Table (and the data), the more suspect the assumption of stability becomes.</em></p>
</section><section class="level3"><h3 id="representativeness">Representativeness<a class="anchor" aria-label="anchor" href="#representativeness"></a>
</h3>
<blockquote>
<p>Representativeness, or the lack thereof, concerns two relationships among the rows in the Population Table. The first is between the data and the other rows. The second is between the other rows and the Preceptor Table.</p>
</blockquote>
<p>Ideally, we would like both the Preceptor Table <em>and</em> our data to be random samples from the population. If so, then the assumption of representativeness is met. Sadly, this is almost never the case.</p>
<p>Stability looks across time periods. Representativeness looks within time periods.</p>
<p>We mention specific examples of two potential problems. First, is our data representative of the population? Rarely! Second, are the rows associated with the Preceptor Table representative of the population? Again, almost never!</p>
<p>Provide specific examples of how a lack of representativeness might be a problem, one large enough to affect your ability to answer the question.</p>
<p>But, to continue the analysis, we always assume/pretend that the rows from both the data and the Preceptor Table are representative <em>enough</em> of the relevant time period from within the larger population from which both are drawn.</p>
</section><section class="level3"><h3 id="unconfoundedness">Unconfoundedness<a class="anchor" aria-label="anchor" href="#unconfoundedness"></a>
</h3>
<blockquote>
<p>Unconfoundedness means that the treatment assignment is independent of the potential outcomes, when we condition on pre-treatment covariates. A model is <em>confounded</em> if this is not true.</p>
</blockquote>
<p>This assumption is only relevant for causal models. We describe a model as “confounded” if this is not true. The easiest way to ensure unconfoundedness is to assign treatment randomly.</p>
<p>If the model is predictive, then unconfoundedness is not a concern. Just mention that fact in a sentence at the end of the section on representativeness. But, if the model is causal, then we need a section devoted to this topic.</p>
<p>If treatment assignment was random, then unconfoundedness is guaranteed, although experienced researchers often worry about the exact process involved in such “random” assignment. If, however, treatment assignment was not random, then there will always be a concern that it is correlated with potential outcomes. Discuss at least two scenarios in which this might be a concern. But then, as usual, conclude that, although there might be some issues with confoundedness, they are probably small enough to not worry about.</p>
<p>Just because Wisdom points us toward a Population Table with <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>N</mi><annotation encoding="application/x-tex">N</annotation></semantics></math> rows does not mean we need to keep all <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>N</mi><annotation encoding="application/x-tex">N</annotation></semantics></math> rows, especially if creating a model which covers all rows is hard/impossible. We can just simplify the claims we are making about the world by removing some rows. Getting rid of rows will usually necessitate an adjustment to the question we are trying to answer. Again, data science is an iterative process.</p>
<p>The Justice section concludes with a sentence or two about how, despite any problems with the core assumptions of stability, representativeness and unconfoundedness, we can still proceed to next steps because the assumptions hold enough.</p>
<p>The last step is to revisit the key sentences from the Wisdom section. Recall:</p>
<blockquote>
<p><em>Using data from a 2012 survey of Boston-area commuters, we seek to understand the relationship between income and political ideology in Chicago and similar cities in 2020. In particular, what percentage of individuals who make more than $100,000 per year are liberal?</em></p>
</blockquote>
<p>Are these sentences still correct, or does a serious consideration of the assumptions of stability, representativeness and unconfoundedness require us to modify them? The answer, of course, is that the assumptions are never perfect! So, we have an obligation to add a sentence or two which highlights (no more than) one or two concerns. Examples:</p>
<blockquote>
<p><em>There is some concern that survey participants may not be perfectly representative of the underlying population.</em></p>
</blockquote>
<blockquote>
<p><em>The relationship between income and ideology may have changed over that eight year period.</em></p>
</blockquote>
<p>There is no need to use technical terms like “stability.” However, most readers will understand what “representative” means. The key point is <em>honesty</em>. We have an obligation to at least mention some possible concerns. Our new paragraph:</p>
<blockquote>
<p><em>Using data from a 2012 survey of Boston-area commuters, we seek to understand the relationship between income and political ideology in Chicago and similar cities in 2020. In particular, what percentage of individuals who make more than $100,000 per year are liberal? The relationship between income and ideology may have changed over that eight year period.</em></p>
</blockquote>
</section></section><section class="level2"><h2 id="courage">Courage<a class="anchor" aria-label="anchor" href="#courage"></a>
</h2>
<blockquote>
<p>Courage starts with math, explores models, and then creates the Data Generating Mechanism.</p>
</blockquote>
<p><strong>Courage</strong> is the third <a href="https://en.wikipedia.org/wiki/Cardinal_virtues" class="external-link">Cardinal Virtue</a> in data science. Justice gives us the Population Table. Courage creates the data generating mechanism. We first specify the mathematical formula which connects the outcome variable we are interested in with the other data that we have. We explore different models. We need to decide which variables to include and to estimate the values of unknown parameters. We check our models for consistency with the data we have. We avoid hypothesis tests. We select one model, the data generating mechanism.</p>
<p>Courage begins by a discussion of the functional form we will be using. This is usually straight-forward because it follows directly from the type of the outcome variable: continuous means a linear model, two categories (binary) implies logistic, and more-than-two categories suggests multinomial logistic. We provide the mathematical formula for this model, using <code>y</code> and <code>x</code> as variables. We don’t yet know the number of right-hand side variables to include, much less which ones. So, the formula is generic.</p>
<p>The rest of the discussion is broken up into three sections: “Models,” “Tests,” and “Data Generating Mechanism.”</p>
<section class="level3"><h3 id="models">Models<a class="anchor" aria-label="anchor" href="#models"></a>
</h3>
<p>When exploring different models, we need to decide which variables to include and to estimate the values of unknown parameters. We estimate the models and then print out the model results. We do not give another version of the math, or use <code>tbl_regression()</code> yet. The goal is to explore and interpret different models.</p>
<p>If a parameter’s estimated value is more than 2 or 3 standard errors away from zero, we generally keep that parameter (and its associated variable) in the model. This is, probably, a variable which “matters.” The main exception to this rule is a parameter whose value is so close to zero that changes in its associated variable, within the general range of that variable, can’t change the value of the outcome by much.</p>
<p>Depending on the chapter, we will use different tools to choose among the different possible models.</p>
<section class="level4"><h4 id="interpreting-parameters">Interpreting Parameters<a class="anchor" aria-label="anchor" href="#interpreting-parameters"></a>
</h4>
<p>Interpreting the meaning of parameter estimates takes practice. Consider a simple linear model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">linear_reg</span><span class="op">(</span>engine <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">fit</span><span class="op">(</span><span class="va">att_end</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">age</span>, data <span class="op">=</span> <span class="va">trains</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">tidy</span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">TRUE</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">term</span>, <span class="va">estimate</span>, <span class="va">conf.low</span>, <span class="va">conf.high</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  term             estimate conf.low conf.high
  &lt;chr&gt;               &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        9.58     7.51     11.6
2 sexMale           -0.829   -1.86      0.207
3 treatmentTreated   1.41     0.364     2.46
4 age               -0.0143  -0.0572    0.0286</code></pre>
</div>
</div>
<p>Let’s go through some example Q&amp;A, followed by commentary:</p>
<p><strong>Q:</strong> Write a sentence interpreting the -0.83 estimate for <code>sexMale</code>.</p>
<p><strong>A:</strong> When comparing men with women, men have a 0.83 lower value for <code>att_end</code>, meaning that they are more liberal about immigration, relative to women, conditional on the other variables in the model.</p>
<p>Whenever we consider non-treatment variables, we must never use terms like “cause,” “impact” and so on. We can’t make any statement which implies the existence of more than one potential outcome based on changes in non-treatment variables. We can’t make any claims about within row effects. Instead, we can only compare across rows. Always use the phrase “when comparing X and Y” or something very similar.</p>
<p>The phrase “conditional on the other variables in the model” is important. It could be shortened to “conditional on the model.” This phrase acknowledges that there are many, many possible models, just considering all the different combinations of independent variables we might include. Each one would produce a different coefficient for <code>sexmale</code>. None of these is the <em>true</em> coefficient. Any claim we make about -0.83, or any specific number, is always conditional on the fact that we assume that this model is true, that these covariates, and no others, belong in the regression. Does that mean that we always use the phrase? No. We leave it out all the time. But it is always understood to be there by knowledgeable readers.</p>
<p><strong>Q:</strong> Write a sentence interpreting the confidence interval for <code>sexMale</code>.</p>
<p><strong>A:</strong> We do not know the true value for the coefficient for <code>sexMale</code>, but we can be 95% confident that it lies somewhere between -1.86 and 0.21.</p>
<p>Because we are Bayesians, we believe that there is a true value and that the confidence or credible or uncertainty interval includes it at the stated level.</p>
<p>Most of the time parameters in a model have no direct relationship with any population parameter in which we might be interested. This is especially true in complex and/or non-linear models. That is, in those cases, a coefficient like <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>β</mi><mn>1</mn></msub><annotation encoding="application/x-tex">\beta_1</annotation></semantics></math> does not “mean” anything. But, in simple, small, linear models, it sometimes happens that a parameter does correspond to something real. In this case, the coefficient of <code>sexmale</code> is the difference between the population average of <code>att_end</code> for men and women, adjusting for the other variables in the model.</p>
<p><strong>Q:</strong> Interpret the 1.41 estimate for <code>treatmentTreated</code>.</p>
<p><strong>A:</strong> If this is a causal model, then the average causal effect of receiving the treatment of hearing Spanish-speakers on the train platform, relative to the control, is to have a 1.41 higher value for <code>att_end</code>, meaning that the treatment, relative to the control, makes one more conservative about immigration.</p>
<p><strong>A:</strong> If this is a predictive model, then, if we compare people who receive the treatment with people who receive the control, the treated people have, on average, a 1.41 more conservative attitude toward immigration, adjusting for other individual characteristics.</p>
<p>The interpretation of a treatment variable is very different than the interpretation of a standard covariate. The key point is that there is no such thing as a causal (versus preditive) data set nor a causal (versus predictive) R code formula. You can use the same data set (and the same R code!) for both causal and predictive models. The difference lies in the assumptions you make.</p>
<p><strong>Q:</strong> Interpret the 0.36 to 2.46 interval for the <code>treatmentTreated</code> coefficient.</p>
<p><strong>A:</strong> Our best estimate for the average causal effect is 1.41, meaning that being treated makes someone 1.41 units more conservative about immigration. Yet, the true value could be lower or higher. We are 95% certain that the true effect is somewhere between 0.36 to 2.46.</p>
<p><strong>Q:</strong> Interpret the -0.01 estimate for <code>age</code>.</p>
<p><strong>A:</strong> If we compare one group of people ten years older than another, the older group will, on average, have an attitude toward immigration 0.1 unit lower, i.e., less conservative.</p>
<p>Numeric variables are harder than binary variables because there are no longer just two well-defined groups to compare with each other. We must create those two groups ourselves. Fortunately, as long as there are no interaction terms, we can just pick two groups with any values for the variable. The most common two groups differ by one unit of the variable. But it is quite common to use groups which differ by more/less if doing so seems sensible and/or if it makes the math easier. In this case, two groups which differ by 10 years makes sense for both reasons.</p>
<p>What about non-linear models, or linear models with lots of interaction terms?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">logistic_reg</span><span class="op">(</span>engine <span class="op">=</span> <span class="st">"glm"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">fit</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html" class="external-link">as.factor</a></span><span class="op">(</span><span class="va">arrested</span><span class="op">)</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">race</span>, data <span class="op">=</span> <span class="va">stops</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">tidy</span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">term</span>, <span class="va">estimate</span>, <span class="va">conf.low</span>, <span class="va">conf.high</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 4
  term         estimate conf.low conf.high
  &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   -2.56    -2.69     -2.44
2 sexmale        0.368    0.352     0.385
3 raceblack      1.19     1.07      1.31
4 racehispanic   0.805    0.674     0.939
5 raceother      0.337   -0.0537    0.700
6 raceunknown   -0.0824  -0.262     0.0965
7 racewhite      0.928    0.806     1.05  </code></pre>
</div>
</div>
<p>With a linear model, all these interpretations are fairly straightforward. With any other type of model, the math is too difficult to do in your head. You can’t just look at a coefficient of 5 and know what it means in magnitude. But you can tell the direction, that a positive 5 means that higher values of the covariate are associated with higher values of the outcome variable. So, with anything other than linear models, we restrict ourselves to direction and significance interpretations.</p>
<p><strong>Q:</strong> Write a sentence interpreting the 0.37 estimate for <code>sexmale</code>.</p>
<p><strong>A:</strong> In comparison with women, men are more likely to be arrested.</p>
<p>Categorical variables (with <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>N</mi><annotation encoding="application/x-tex">N</annotation></semantics></math> categories), like sex (with two values), are always replaced with (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>N</mi><mo>−</mo><mn>1</mn></mrow><annotation encoding="application/x-tex">N-1</annotation></semantics></math>) 0/1 dummy variables like <code>sexMale</code>.</p>
<p>We can’t (easily) know how big 0.37 is. Because the model is non-linear, you can’t (easily) determine whether men are 1% or 50% more likely to be arrested.</p>
<p><strong>Q:</strong> Write a sentence interpreting the 1.07 to 1.31 confidence interval for <code>raceblack</code>.</p>
<p><strong>A:</strong> In comparison with Asian/Pacific Islanders, Blacks are more likely to be arrested. In fact, they are more likely to be arrested than any other racial group.</p>
<p>Dummy variables must always be interpreted in the context of the base value for that variable, which is generally included in the intercept. For example, the base value here is “asian/pacific islander.” (The base value is the first alphabetically by default for character variables. However, if it is a factor variable, you can change that by setting the order of the levels by hand.)</p>
<p>We look for two things in the confidence interval. First, does it exclude zero? If not, then we can’t be sure if the relationship is positive or negative. Second, does it overlap with the confidence intervals for other dummy columns derived from this variable? If so, then we can be sure that the ordering as to which comparisons are bigger. If there is overlap, as for example between <code>raceother</code> and <code>raceunknown</code>, we can’t be sure how the average comparison would go. Because the estimate for <code>raceother</code> is larger than the estimate for <code>raceunknown</code>, our best guess is that members of the former group are more likely to be arrested. But, because the confidence intervals overlap, there is a good chance (more than 5% certainly) that the ordering is the opposite.</p>
<p>We recommend the verb “adjust” in place of “control” when discussing the effect of including other variables in the model. Example: “The causal effect of exposure to Spanish-speakers is 1.5, adjusting for other variables like age and party.” The word “adjusting” is better than the word “controlling” because it demonstrates some humility.</p>
<p>The more advanced our models, the less relevant are these sorts of interpretations. After all, we don’t really care about parameters, much less how to interpret them. Parameters are imaginary, like unicorns. We care about answers to our questions. Parameters are tools for answering questions. They aren’t interesting in-and-of themselves. <em>In the modern world, all parameters are nuisance parameters.</em></p>
<!-- DK: Should we provide an example Q/A for interpreting the intercept? -->
</section></section><section class="level3"><h3 id="tests">Tests<a class="anchor" aria-label="anchor" href="#tests"></a>
</h3>
<p>We check our models for consistency with the data we have using posterior predictive testing. We avoid hypothesis tests.</p>
</section><section class="level3"><h3 id="data-generating-mechanism">Data Generating Mechanism<a class="anchor" aria-label="anchor" href="#data-generating-mechanism"></a>
</h3>
<p><strong>Data Generating Mechanism</strong> (DGM) is also called the data generating model or the <a href="https://en.wikipedia.org/wiki/Data_generating_process" class="external-link">data generating process</a>. The <em>true</em> DGM is the reality of the world, the physical process which actually generates the data which we observe. The <em>estimated</em> DGM is the mathematical formula we create which models the true DGM, which we can never know. In Temperance, we will use the estimated DGM to draw inferences about our Quantities of Interest.</p>
<p>We create a final model, the data generating mechanism. We provide the math for this model, using variable names instead of <code>y</code> and <code>x</code> as we did at the start of the chapter. We present the final parameter estimates nicely, using the <strong>gtsummary</strong> package.</p>
<p>The model you have made by the end of Courage is almost always too complex to answer the simple question you started with, because the question rarely specifies the values of all the covariates which are included in the model. But any covariates or treatments which are part of the initial question(s) must be included in the model, otherwise we can’t answer any questions about them at all.</p>
<p>The DGM section ends with a clear statement in English, in its own paragraph, describing the model. That is, what are the two sentences which a student would say at a presentation describing the model. The first sentence specifies the model, including making clear the units, outcome and key covariates. (No need to use the terms “units,” “outcomes,” and so on.) The second sentence tells us something about the model, generally the relationship between one of the covariates and the outcome variable. In general, there is no discussion of specific numbers or their uncertainty. First, who cares? Parameter estimates are boring and irrelevant. Second, the Temperance section is where we answer the original question. Example:</p>
<blockquote>
<p><em>We modeled being liberal, a binary TRUE/FALSE variable, as a logistic function of income. Individuals with higher income were more likely to be liberal.</em></p>
</blockquote>
<p>Update our concluding paragraph with this addition:</p>
<blockquote>
<p><em>Using data from a 2012 survey of Boston-area commuters, we seek to understand the relationship between income and political ideology in Chicago and similar cities in 2020. In particular, what percentage of individuals who make more than $100,000 per year are liberal? The relationship between income and ideology may have changed over that eight year period. We modeled being liberal, a binary TRUE/FALSE variable, as a logistic function of income. Individuals with higher income were more likely to be liberal.</em></p>
</blockquote>
<p>Feel free to use “I” instead of “We” if the project is solo.</p>
</section></section><section class="level2"><h2 id="temperance">Temperance<a class="anchor" aria-label="anchor" href="#temperance"></a>
</h2>
<blockquote>
<p>Temperance uses the Data Generating Mechanism to answer the questions with which we began. Humility reminds us that this answer is always a lie. We can also use the DGM to calculate many similar quantities of interest, displaying the results graphically.</p>
</blockquote>
<p><strong>Temperance</strong> is the fourth <a href="https://en.wikipedia.org/wiki/Cardinal_virtues" class="external-link">Cardinal Virtue</a> in data science. Courage gave us the data generating mechanism. Temperance guides us in the use of the DGM — or the “model” — we have created to answer the questions with which we began. We create posteriors for the quantities of interest. We should be modest in the claims we make. The posteriors we create are never the “truth.” The assumptions we made to create the model are never perfect. Yet decisions made with flawed posteriors are almost always better than decisions made without them.</p>
<p>The two sub-sections of Temperance are: Questions and Answers, and Humility.</p>
<p>It is important to monitor our language. We do not believe that changes in <code>election_age</code> “cause” changes in <code>lived_after</code>. That is obvious. But there are some words and phrases — like “associated with” and “change by” — which are too close to causal. Be wary of their use. <em>Always think in terms of comparisons when using a predictive model.</em> We can’t change <code>election_age</code> for an individual candidate. We can only compare two candidates (or two groups of candidates).</p>
<section class="level3"><h3 id="questions-and-answers">Questions and Answers<a class="anchor" aria-label="anchor" href="#questions-and-answers"></a>
</h3>
<p>We go back to the question(s) with which we started the journey. We discuss how that question has evolved, in a back-and-forth process by which we try to ensure that the data we have and the question we ask are close enough to make the process plausible.</p>
<p>We revisit the Preceptor Table, at least conceptually. We emphasize that the DGM allows us to fill in missing outcomes in the Preceptor Table, thereby allowing us to answer our questions.</p>
<p>Key issue is the connection between the DGM (either true or estimated) and the Preceptor Table. The connection is tricky! Not even sure I understand it. The DGM can be used to “fill in” all the missing elements of the Preceptor Table, but there will always be some associated uncertainty. Even with the true DGM, we don’t know what <code>att_end</code> Joe would have had under treatment, we just have a posterior for that variable, a way to make draws.</p>
<p>Idea: Use the DGM to create one complete Preceptor Table. In that draw, Joe is a 6 for <code>att_end</code>. Then, do another draw. Joe is a 5. Do a thousand draws. You then have a thousand Preceptor Tables. Calculate the Quantity of Interest for each Preceptor Table. The 1,000 values are the posterior for your QoI.</p>
<p>Would be great to make a cool animation of this, perhaps with a simple example. Would be fun to have a similar animation for each chapter. Great summer project!</p>
<p>We use the data generating mechanism from Courage to answer the question. This is, obviously, the core of the Temperance section.</p>
<section class="level4"><h4 id="plots-from-marginaleffects">Plots from <strong>marginaleffects</strong>
<a class="anchor" aria-label="anchor" href="#plots-from-marginaleffects"></a>
</h4>
<p>We walk the student through several plots created with the <strong>marginaleffects</strong> package. The plots are generally increasing in complexity. We always tell the student which plot to create by giving them the exact code. If possible, the knowledge drop tries to connect the plot to the table of regression results we interpreted above. Example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fit_attitude</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span>engine <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">fit</span><span class="op">(</span><span class="va">att_end</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">age</span>, data <span class="op">=</span> <span class="va">trains</span><span class="op">)</span></span></code></pre></div>
</div>
<p><strong>Example 1</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">plot_predictions</span><span class="op">(</span><span class="va">fit_attitude</span>,</span>
<span>                 condition <span class="op">=</span> <span class="st">"sex"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cardinal_virtues_files/figure-html/unnamed-chunk-6-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the expected value of attitudes toward immigration, conditional on the model, for women and men. Women have higher (more conservative) attitudes toward immigration, adjusting for age and treatment. This is consistent with the negative estimated coefficient for <code>sexMale</code> of -0.83.</p>
<p><strong>Example 2</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">plot_predictions</span><span class="op">(</span><span class="va">fit_attitude</span>,</span>
<span>                 condition <span class="op">=</span> <span class="st">"treatment"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cardinal_virtues_files/figure-html/unnamed-chunk-7-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the expected value of attitudes toward immigration, conditional on the model, for those exposed to treatment (Spanish-speakers on the train platform) and control. Treated individuals have higher (more conservative) attitudes toward immigration, adjusting for age and sex This is consistent with the positive estimated coefficient for <code>treatmentTreated</code> of 1.41.</p>
<p><strong>Example 3</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">plot_predictions</span><span class="op">(</span><span class="va">fit_attitude</span>,</span>
<span>                 condition <span class="op">=</span> <span class="st">"age"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cardinal_virtues_files/figure-html/unnamed-chunk-8-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the expected value of attitudes toward immigration, conditional on the model, for individuals of different ages. Younger people have higher (more conservative) attitudes toward immigration, adjusting for treatment and sex This is consistent with the negative estimated coefficient for <code>age</code> of -0.01.</p>
<p><strong>Example 4</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">plot_predictions</span><span class="op">(</span><span class="va">fit_attitude</span>,</span>
<span>                 condition <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"treatment"</span>, <span class="st">"age"</span>, <span class="st">"sex"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cardinal_virtues_files/figure-html/unnamed-chunk-9-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the expected value of attitudes toward immigration, conditional on the model, for individuals of different treatment assignments, ages and sexes.</p>
<p>We are often just as interested in <em>comparisons</em> as we are in <em>predictions</em>. It is tempting to think that we can deduce comparisons by just subtracting one prediction from another. This mostly works for the center of the distribution but it definitely does not work for the confidence interval. Fortunately, <strong>marginaleffects</strong> provides the <code>plot_comparison()</code> function for this purpose.</p>
<p><strong>Example 5</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">plot_comparisons</span><span class="op">(</span><span class="va">fit_attitude</span>,</span>
<span>                 variables <span class="op">=</span> <span class="st">"treatment"</span>,</span>
<span>                 condition <span class="op">=</span> <span class="st">"treatment"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="cardinal_virtues_files/figure-html/unnamed-chunk-10-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the expected value of the <em>difference</em> in attitudes toward immigration between Treated and Control, conditional on the model. Treated have higher (more conservative) attitudes toward immigration, adjusting for age and sex. This is consistent with the negative estimated coefficient for <code>treatmentTreated</code> of 1.41.</p>
<p>The relationship between <code>plot_predictions()</code> and <code>plot_comparisons()</code> is subtle, but the central point is that, if you want to look at the difference or ratio or any other function of more than one expected value, you must use <code>plot_comparisons()</code>.</p>
<p>Further comments on <code>plot_comparisons()</code>:</p>
<ul>
<li><p>The values for the <code>condition</code> argument determine the structure of the plot. The first value is the x-axis, the second is the color and the third separates the plots into different panes.</p></li>
<li><p>The value for the <code>variables</code> argument specifies the variable around which any <em>comparisons</em> are organized.</p></li>
<li><p>If a model is not <em>rich</em> enough — meaning enough terms/interactions/non-linearities — there won’t be enough complexity for a complex call to <code>plot_comparisons()</code>.</p></li>
</ul>
<p>The section always concludes with a one sentence summary of our final conclusion. This summary does not include any technical terms. It is meant for non-statisticians. It is something which we might say in explaining our take-away conclusion to a non-statistician. It will always feature at least one number, and our uncertainty associated with that number. Example:</p>
<blockquote>
<p><em>55% (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>±</mi><annotation encoding="application/x-tex">\pm</annotation></semantics></math> 2%) of the people who make more than $100,000 per year are liberal.</em></p>
</blockquote>
<p>or</p>
<blockquote>
<p><em>Of the people making $100,000 or more per year, about 55% are liberal, although the true number could be as low as 53% or as high as 57%.</em></p>
</blockquote>
</section><section class="level4"><h4 id="scaling-the-qoi">Scaling the QoI<a class="anchor" aria-label="anchor" href="#scaling-the-qoi"></a>
</h4>
<p>Some cases, like these, feature numbers which have a natural interpretation. We know what percentages are. But many outcomes are measured in units which are more difficult to interpret. For example:</p>
<blockquote>
<p><em>The causal effect of smaller class size on math exam scores was 10 points.</em></p>
</blockquote>
<p>The reader does not know if 10 points is a big or small effect because she doesn’t know anything about the range of scores which students get on this exam. The most common approach to this problem is to “standardize” the causal effect by dividing by the standard deviation of the outcome. For example, if the standard deviation of all the math exam scores is 50, then we would re-write this as:</p>
<blockquote>
<p><em>The standardized causal effect of smaller class size on math exam scores was 0.2.</em></p>
</blockquote>
<p>Depending on the field, there are a variety of terms for describing a raw causal effect divided by the standard deviation, including “sigmas” — derived from the use of the Greek letter <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>σ</mi><annotation encoding="application/x-tex">\sigma</annotation></semantics></math> as a symbol for the standard deviation. So, we might also write:</p>
<blockquote>
<p><em>The causal effect of smaller class size on math exam scores was 0.2 sigmas.</em></p>
</blockquote>
<p>The raw effect size of 10 is 20% a standard deviation (50). If it were 50, we would speak instead one “one sigma” which is one standard deviation.</p>
<p>Another common term for this divide-by-the-standard deviation standardization is “effect size.” So:</p>
<blockquote>
<p><em>The effect size of smaller class size on math exam scores was 0.2.</em></p>
</blockquote>
<p>Here is another approach for tackling a problem in which the scale does not have a natural interpretation. Consider:</p>
<blockquote>
<p><em>The causal effect of hearing Spanish-speakers is a more conservative attitude toward immigration, a change of about 1.5 (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>±</mi><annotation encoding="application/x-tex">\pm</annotation></semantics></math> 0.5) on a 15 point scale.</em></p>
</blockquote>
<p>This is correct, as far as it goes, but we have no idea if 1.5 is a “big” or “small” change. We need some perspective.</p>
<blockquote>
<p><em>The causal effect of hearing Spanish-speakers is a more conservative attitude toward immigration, a change of about 1.5 (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>±</mi><annotation encoding="application/x-tex">\pm</annotation></semantics></math> 0.5) on a 15 point scale. For perspective, the difference between Democrats and Republicans on that same scale is about 2.1.</em></p>
</blockquote>
</section><section class="level4"><h4 id="confidencecredibleuncertainty-intervals">Confidence/Credible/Uncertainty Intervals<a class="anchor" aria-label="anchor" href="#confidencecredibleuncertainty-intervals"></a>
</h4>
<p>Terminology is important. The best words depend on your audience. An example involves how you describe your uncertainty, the interval around your best estimate of the quantity of interest. The terminology above — 1.5 (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>±</mi><annotation encoding="application/x-tex">\pm</annotation></semantics></math> 0.5) — works well for a general audience. But you may want to be more precise as to the meaning of that interval. Consider some options:</p>
<ul>
<li><p><em>95% interval of 0.5 to 1.5</em>. The use of the word “interval,” without an associated adjective, is a way to avoid the entire debate. The meaning is almost certainly the Bayesian one: The 95% percentile range on my posterior for the true causal effect goes from 0.5 to 1.5.</p></li>
<li><p><em>95% confidence interval of 0.5 to 1.5</em>. The adjective “confidence” is used by two different sorts of people. First are Frequentists, whose philosophy is the traditional approach to statistics and still in control at institutions like the College Board. The Frequentist meaning is that, if we followed the same approach in 100 similar problems then, 95% of the time, our confidence interval would include the true value. If you don’t understand this, don’t worry. You will never work for a Frequentist. The second sort of person who uses the adjective “confidence” is someone who is actually Bayesian, like us, but doesn’t care about annoying Frequentists.</p></li>
<li><p><em>95% credible interval of 0.5 to 1.5</em>. The adjective “credible” is the <a href="https://en.wikipedia.org/wiki/Credible_interval" class="external-link">Bayesian analogue</a> to “confidence.” Other <a href="https://statmodeling.stat.columbia.edu/2022/04/05/confidence-intervals-compatability-intervals-uncertainty-intervals/" class="external-link">Bayesians</a> who don’t want to annoy Frequentists will often replace “confidence” with “uncertainty” to be polite. But, being Bayesians, their meaning is always the same: There is a 95% chance that the true value is between 0.5 and 1.5.</p></li>
</ul>
<p>The main takeaway is that the vast majority of people will not care if you use “confidence interval” or “credible interval” or “uncertainty interval.” They will interpret any of these phrases in the Bayesian way: there is an X% chance — where X is most often 95 but can take on other values — that the true value lies within the interval.</p>
</section><section class="level4"><h4 id="final-paragraph">Final Paragraph<a class="anchor" aria-label="anchor" href="#final-paragraph"></a>
</h4>
<p>Depending on the context, you might have more than one Quantity of Interest to discuss. But there must be at least one. You are now ready to provide the entire concluding paragraph.</p>
<blockquote>
<p><em>Using data from a 2012 survey of Boston-area commuters, we seek to understand the relationship between income and political ideology in Chicago and similar cities in 2020. The relationship between income and ideology may have changed over that eight year period. We modeled the status of having a liberal political orientation, a binary TRUE/FALSE variable, as a logistic function of income. Individuals with higher income were more likely to be liberal. Of the people making $100,000 or more per year, about 55% are liberal, although the true number could be as low as 53% or as high as 57%.</em></p>
</blockquote>
<p>Note that we have deleted the rhetorical question — “In particular, what percentage of individuals who make more than $100,000 per year are liberal?” — from the start of the paragraph. It is no longer necessary.</p>
<p>The final result of data science project is a paragraph like this one. Data science begins with a question and some data. It ends with a paragraph and, ideally, some graphics.</p>
<p>Of course, real data science projects never involve a single question. Instead, the starting question leads you to create a DGM which can answer it but which also can answer lots and lots of other questions. Which is cool. In fact, it is often possible to create a graphic which answers lots of questions at once. That is ideal. (The Michigan postcard example is great.)</p>
<p>A really good data science project always ends with a cool graphic which answers lots of questions and a paragraph like the one above which picks out one answer to highlight.</p>
<p>The Questions and Answers section ends with that final paragraph.</p>
</section></section><section class="level3"><h3 id="humility">Humility<a class="anchor" aria-label="anchor" href="#humility"></a>
</h3>
<p>Temperance guides us in the use of the DGM to answer the questions with which we began.</p>
<p>The Humility section always begins with single sentence, something along the lines of:</p>
<p><em>We can never know the truth.</em></p>
<p>Over time, we hope to collect a serious of quotations along this theme.</p>
<p>Having answered the question, we now (quickly) review all the reasons why our answer might be wrong. Review the <em>specific</em> concerns we had about validity, stability, representativeness, and (if a causal model) unconfoundedness. Those concerns remain.</p>
<p>Review the three levels of “truth”: Knowing all the entries in the Preceptor Table, knowing the true DGM, and then using our estimated DGM. (This explanation can become more sophisticated as the chapters progress.)</p>
<p>We can never know all the entries in the Preceptor Table. That knowledge is reserved for God. If all our assumptions are correct, then our DGM is true, it accurately describes the way in which the world works. There is no better way to predict the future, or to model the past, than to use it. Sadly, this will only be the case with toy examples involving things like coins and dice. We hope that our DGM is close to the true DGM but, since our assumption are never perfectly correct, our DGM will always be different. The estimated magnitude and importance of that difference is a matter of judgment.</p>
<p>The problem with our concluding paragraph is that it implies that our DGM is the truth, rather than just an imperfect approximation of the true DGM. There are two main ways in which are DGM might be wrong. First, the central portion of our estimate, 55% in this case, might be wrong. We might be biased low or high. It is hard to know what to do about that, other than to be aware.</p>
<p>The second way that our DGM might be wrong, relative to the true DGM, is that our uncertainty interval, the 4% from 53% to 57%, might be off. It might be too narrow or too wide. In reality, however, it is almost certainly too narrow, relative to the true DGM. Problems with our assumptions, which are inevitable, almost always make our confidence intervals too narrow.</p>
<p>Given these concerns, we provide a new final paragraph. This paragraph is just like the one with which we ended the Questions and Answers section, but with (perhaps) a different mean estimate and (almost always) a wider confidence interval.</p>
<p>In later chapters we should also estimate a different (plausible) DGM and show the answer it provides to our question. That answer will always be different than the one in the concluding paragraph. (Ideally, we choose a small change in the model which produces a large change in the estimates for the QoI.)</p>
<p>Last line in every chapter is always: “The world is always more uncertain than our models would have us believe.”</p>
</section></section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="http://davidkane.info" class="external-link">David Kane</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.3.</p>
</div>

    </footer>
</div>





  </body>
</html>
