---
title: "Data Webscraping"
tutorial:
  id: "data-webscraping"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "Chapter 3: Data -- Webscraping"
---

```{r setup, include = FALSE}
library(learnr)
library(primer.tutorials)
library(tidyverse)
library(rvest)
library(png)
library(grid)

knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 600, 
        tutorial.storage = "local") 
```


## Information
###

```{r information}
quiz(caption = "",
  question_text(
    "Name:",
    answer(NULL, correct = TRUE),
    allow_retry = TRUE,
    try_again_button = "Edit Answer",
    incorrect = NULL),
  question_text(
    "Email:",
    answer(NULL, correct = TRUE),
    allow_retry = TRUE,
    try_again_button = "Edit Answer",
    incorrect = NULL))
```


<!-- This should be a 60 to 90 minutes worth of exercises devoted to webscraping, with a big focus on the rvest package. Also need to teach some CSS and selector gadget. Resources: -->

<!-- https://rvest.tidyverse.org/ -->
<!-- https://github.com/tidyverse/rvest/blob/master/vignettes/articles/selectorgadget.Rmd -->
<!-- https://minecr.shinyapps.io/dsbox-05-moneyinpolitics/ -->
<!-- https://github.com/mdogucu/web-scrape -->


## Submit

```{r context = "setup"}
submission_ui
```

```{r context = "server"}
submission_server()
```
